### ISSUE TITLE
Is it possible to set a timeout on request to AWS ?

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift#101]
Currently finding when I have no network everything stalls. Would be cleaner if I could add a timeout and I could then respond to this.

**Comment by Yasumoto** [comment]
Great call, this would definitely be a good idea to expose.

**Comment by adam-fowler** [comment]
The issues I was seeing here is actually a problem with the HttpClient. If you have no network the ClientBootStrap channelInitializer is never called. The connection will fail but there is nothing to set the response promise to fail. Thus the future.wait() will never return. I have a solution for this but it is dependent on NIO2.0 code. Adding the following after the flatMap() call will catch the error and set the response to fail
```
.flatMapErrorThrowing { error in
                response.fail(error)
                throw error
        }
```

**Comment by adam-fowler** [comment]
Fixed with https://github.com/swift-aws/aws-sdk-swift-core/commit/7e31653b3cb75f24eb096a8cff143c6d40800b03
