### ISSUE TITLE
S3RequestMiddleware provides wrong domain for useast1 region.

### ISSUE THREAD

**Issue by Sassafrass** [swift-aws/aws-sdk-swift#104]
domain is set to `s3-us-east-1.amazonaws.com` but that doesn't work. it should be `s3.amazonaws.com`

**Comment by jonnymacs** [comment]
@Sassafrass yeah you're right. there is some rather old code causing this that's no longer necessary.

Can you try this branch `s3defaultServiceEndpoint`, see if it resolves?

**Comment by Sassafrass** [comment]
I tested `. useast1` and `. uswest2` and both are working on that branch.

**Comment by jonnymacs** [comment]
#105
