### ISSUE TITLE
Dictionaries are not serialised correctly when the service protocol is query

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift#106]
When serialising dictionaries in queries they are currently being serialised as 
```
<dictionary name>.<entry key>=<entry value>
```
The output should be of the form
```
<dictionary name>.entry.N.key=<entry key>
&<dictionary name>.entry.N.value=<entry value>
```
where N is the index of the key, value pair.

An example of this is SNS.createTopic() set one of the attributes and you get a MalformedInput error returned back from AWS.

I have had a look at how to resolve this. The best I've come up with so far is https://github.com/adam-fowler/aws-sdk-swift-core/blob/serialize-dictionary/Sources/AWSSDKSwiftCore/AWSShapes/Dictionary.swift. I have hand replaced some of the dictionaries with this DictionaryShape class in the SNS Shape classes and it fixes the issue.

**Comment by jonnymacs** [comment]
@adam-fowler it appears we are missing support for serializing complex structures to query parameters - here is the [ruby sdk test](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/spec/aws/query/param_builder_spec.rb#L78) that demonstrates some of the other variants.

I assume you looked at JSONSerializer.serializeToFlatDictionary in the core lib? This is where the `<dictionary name>.<entry key>=<entry value>` comes from.

Did you try fixing it there? you might try something like. 

```
for (i, kvp) in dictionary.enumerated() {
    let key = kvp.key2 
    let value = kvp.value
...

flatted["\(key).entry.\(i).key"] = key2 
flatted["\(key).entry.\(i).value"] = value2

```

Let me know I can make a branch for you to try it. I do worry considering how many variants there are it might break something else. It seems pretty clear that a `[String:String]` dict should be serialized this way, so it may make sense to limit the change to just this type of dict.

**Comment by adam-fowler** [comment]
Hi,
I attempted to do the change at the serializeToFlatDictionary() level but realised this wouldn’t be possible. The Json for a dictionary looks pretty much the same as the json for a structure so there is no way to tell them apart when flattening the dictionary. That is why I tried to do this at a point where we knew for sure we were dealing with a dictionary. It’s not the cleanest of changes but it only affects dictionaries used within queries so cannot break anything else. 

I have changes to the code generator that output this new format dictionary for queries. The only problem is when I run the code generator is reorders the parameters for loads of functions.

**Comment by adam-fowler** [comment]
Found a way to fix this. Added a new encodeToQueryDictionary function that creates the query flat dictionary directly from the AWSShape instead of it going via a json structure. The code is in https://github.com/swift-aws/aws-sdk-swift-core/pull/53 along with a bunch of other fixes.

**Comment by adam-fowler** [comment]
Fixed with https://github.com/swift-aws/aws-sdk-swift-core/pull/53
