### ISSUE TITLE
Decoding error on response of ECS.describeServices

### ISSUE THREAD

**Issue by novi** [swift-aws/aws-sdk-swift#109]
While requesting API for `ECS.describeServices`, I have got an error:

```
dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "services", intValue: nil), _DictionaryKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "propagateTags", intValue: nil)], debugDescription: "Cannot initialize PropagateTags from invalid String value NONE", underlyingError: nil))
```

My actual raw json response is:

```
...\"propagateTags\":\"NONE\",...
```

Here is definition of `PropagateTags` in Swift.

```swift
public enum PropagateTags: String, CustomStringConvertible, Codable {
    case taskDefinition = "TASK_DEFINITION"
    case service = "SERVICE"
}
```

`NONE` is missing or models is outdated?

**Comment by jonnymacs** [comment]
Hi @novi 

We pull definitions from the go sdk json, which is also missing the `NONE` case for this enum.

If you want to submit a PR that adds this?

**Comment by adam-fowler** [comment]
This is now fixed by https://github.com/swift-aws/aws-sdk-swift/pull/123
