### ISSUE TITLE
Is it possible to use CognitoIdentityPool for identification? 

### ISSUE THREAD

**Issue by sage444** [swift-aws/aws-sdk-swift#111]
Hello 

Thanks for great library and sorry for lame question. 
I'm porting some old code to new platform and stuck on subject. 

More precise question. Can I expect that this code return `identity` without any configured credentials?
```
let client = CognitoIdentity(region: .useast1)
let request = CognitoIdentity.GetIdInput(identityPoolId: AWSLink.poolId)
let id = try client.getId(request) // <-- locks here
Log.debug(message: "received id: \(id)")
```

Thanks

**Comment by jonnymacs** [comment]
Hello @sage444 

I believe you are experiencing issue #101 where without credentials the code hangs. So to answer your question in short - no, you should not expect the call to return identity without any configured credentials.

**Comment by adam-fowler** [comment]
looks like this can be closed

**Comment by adam-fowler** [comment]
Re-opening.
Much of the CognitoIdentityProvider service doesn't require authentication. I'm assuming this is the same for CognitoIdentity.

**Comment by ezhou7** [comment]
Hi,

Any updates on enabling CognitoIdentity not needing authentication to make certain calls?  I'm currently trying to use CognitoIdentity without access keys:
```
cognitoIdentityClient = CognitoIdentity(region: .useast2)
...
let future = cognitoIdentityClient.getCredentialsForIdentity(input)
```
Just for reference, I saw from this post in the AWS blog (https://aws.amazon.com/blogs/mobile/amazon-rekognition-detects-celebrities-in-ios-app/) which allows Cognito calls without authentication.

I'm just trying to find a way where I don't need to hardcode access key and secret key into the app.

Thanks!

**Comment by adam-fowler** [comment]
The PR is written just waiting for it to be reviewed https://github.com/swift-aws/aws-sdk-swift-core/pull/136

**Comment by ezhou7** [comment]
Thanks!

**Comment by adam-fowler** [comment]
These changes are now on the master branch. Initialise service explicitly setting `accessKeyId` and `secretAccessKey` to "" and requests will go through unsigned. eg
```
let cognitoClient = CognitoIdentity(accessKeyId:"", secretAccessKey:"", region: .useast2)
```
