### ISSUE TITLE
Issue with session tokens?

### ISSUE THREAD

**Issue by ileitch** [swift-aws/aws-sdk-swift#121]
I'm trying to use this SDK with credentials obtained via [Okta](https://www.okta.com/). The Okta integration generates a profile in the credentials file that includes a session token. When using this SDK I always get the error `The AWS Access Key Id you provided does not exist in our records.`

The `aws` CLI tool works without error. I also tested the Ruby SDK which works.

**Comment by adam-fowler** [comment]
@ileitch Can you post your code

**Comment by jonnymacs** [comment]
@adam-fowler @ileitch this may be relevant. If it's a get request to s3 that requires a token you'll see this error. There is a fix in the coming 2.1 release

https://github.com/swift-aws/aws-sdk-swift-core/pull/44/commits/c5e20525b7fc71b013f74baaca7f1f9d163bfc0b

**Comment by jonnymacs** [comment]
@ileitch can you retest with todays 3.0.0 tag?

**Comment by ileitch** [comment]
That fixed it, thanks 👍
