### ISSUE TITLE
S3 Bucket BaseURL

### ISSUE THREAD

**Issue by wieweb** [swift-aws/aws-sdk-swift#128]
Is there a way to get the baseURL of my S3 bucket?
`S3` does have an `AWSClient` with and `endpoint` but the client is internal.

**Comment by adam-fowler** [comment]
If you are looking for the virtual address of a bucket. It is https://<bucketname>.s3.amazonaws.com/.

**Comment by wieweb** [comment]
ok, thank you

**Comment by jonnymacs** [comment]
@wieweb for other regions the `s3` domain prefix will be slightly different. 

The client has a public var called `serviceHost` which will give you this value as a String. then as @adam-fowler says, prefix this with https://<bucketname>

so https://<bucketname>/<s3Client.serviceHost> should be want you want

**Comment by adam-fowler** [comment]
@jonnymacs the s3 virtual addresses don't need the region

**Comment by jonnymacs** [comment]
@adam-fowler really? hmm... even for operations? (like put for example?)
