### ISSUE TITLE
Separate Code Generator into its own Package.swift

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift#145]
**Is your feature request related to a problem? Please describe.**
This came up because @jonnymacs updated the version of SwiftJSON we were using because he needed features in a later version. The Code Generator requires SwiftyJSON but the AWS service libraries don't. This means we are enforcing a version of SwiftyJSON on everyone who uses aws-sdk-swift even though we aren't using it in those libraries.

While enforcing a version of SwiftyJSON on people is not ideal, the real reason this came up was the latest version of SwiftyJSON is really slow and code generation takes forever.

**Describe the solution you'd like**
- Create a separate folder which contains the Code Generator code. With its own Package.swift
- Remove Code Generator and SwiftyJSON dependency from main Package.swift
- Revert to using IBM version of SwiftyJSON

**Comment by jonnymacs** [comment]
#146
