### ISSUE TITLE
CodeGenerator should output Int instead of Int32

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift#149]
The AWS model files have two integer types: `int` and `long`. These are translated to `Int32` and `Int64` respectively. In general in Swift I work with `Int`. It is a minor annoyance I keep having to convert to `Int32` when creating AWS Request structures.

Would it be preferable if the CodeGenerator output `Int` instead of `Int32` for the AWS type `int`

**Comment by Yasumoto** [comment]
I think this is a good idea! From [the docs](https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#ID319):

> Unless you need to work with a specific size of integer, always use Int for integer values in your code. This aids code consistency and interoperability.
