### ISSUE TITLE
PutObjectRequest Fails with STS

### ISSUE THREAD

**Issue by kperson** [swift-aws/aws-sdk-swift#151]
**Description**
When executing a PutObjectRequest I receive the following error:
```
accessDenied(message: Optional("RequestId: 4059FAA108A45F89, HeadersNotSigned: x-amz-security-token, Message: There were headers present in the request which were not signed, HostId: p013uVEP7DHgqGkbCe/zsjuASVE0b9h9a7Gb37OfnuPmFnNeMZ5VnILzvi9orDLzHtfn1yNEzLA="))
```

**To Reproduce**
1. Execute a put object request in a lambda environment (custom runtime)

**Expected behavior**
1. Request succeeds

**Setup**
 - OS: Amazon Linux (lambda)
 - Version: 3.1.0
 - Authentication mechanism: Amazon STS

**Additional context**
I don't have this issue with SNS or SQS, just S3.

**Comment by adam-fowler** [comment]
Hi @kperson, 
Checkout pull request https://github.com/swift-aws/aws-sdk-swift-core/pull/99
By the way how are you passing the session token to the PutObject command? I noticed we don't have a way to pass full Credentials to a service via a function parameter. Are you using the EnvironmentCredentials()?

**Comment by kperson** [comment]
@adam-fowler I am just allowing for a credential provider to be selected, it would be `EnvironementCredential` (lambda sets AWS_SECRET_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN environment variables automatically).

It looks like your PR would resolve the issue! Thank you.
