### ISSUE TITLE
Invalid Regex for MediaConvert HlsGroupSettings.validate()

### ISSUE THREAD

**Issue by kyleishie** [swift-aws/aws-sdk-swift#160]
When using the MediaConvert API I ran into an issue where setting "s3://exaple.bucket.name/path/" as the HlsGroupSettings.destination resulted in the following error being thrown.

```
validationError(message: Optional("CreateJobRequest.settings.outputGroups[].outputGroupSettings.hlsGroupSettings.destination (s3://exaple.bucket.name/path/) does not match pattern ^s3:\\/\\/."))
```

I forked this repo, updated the regex to "^s3:\\/\\/.*", and the request worked as expected.

I'm not sure if this is an issue that I should submit a PR for as I believe this is generated code. How can I go about making sure this fix is included in the repo?

**Comment by adam-fowler** [comment]
Hi @kyleishie,

Sorry about this. I think I might have been too severe with the regex matching. I was expecting it to match the whole string and not that a match could be found in the string. All the services I had checked were fine. 

https://github.com/swift-aws/aws-sdk-swift-core/pull/108

**Comment by adam-fowler** [comment]
https://github.com/swift-aws/aws-sdk-swift-core/pull/108 has been merged
