### ISSUE TITLE
MediaConvert HTTP 415 Unsupported Media Type

### ISSUE THREAD

**Issue by kyleishie** [swift-aws/aws-sdk-swift#163]
MediaConvert is currently configured to use ServiceProtocolType.restjson but this results in HTTP 415 errors.  Switching to ServiceProtocolType.json fixes the issue.

**Comment by adam-fowler** [comment]
Can you point out where you are changing the service protocol type. 
Also can you supply some code that replicates this issue.

**Comment by adam-fowler** [comment]
I've verified MediaConvert does use a rest-json protocol. The service must be showing an issue in our implementation of the rest-json protocol. Changing the protocol to json could have undefined results.

**Comment by kyleishie** [comment]
> Can you point out where you are changing the service protocol type.
In MediaConvert.init when the AWSClient is created.

> Also can you supply some code that replicates this issue.
So far I have confirmed that both createJob and ListJobs have this issue.  I suspect that all of the calls for this client have this issue but I haven't tested them yet.  

You will have to input your credentials and endpoint for this.  Endpoint can be found under MediaConvert > Account.

```
import Foundation
import MediaConvert

let mediaConvertClient = MediaConvert(accessKeyId: "",
                                      secretAccessKey: "",
                                      region: .useast1,
                                      endpoint: "")

let createJobRequest = MediaConvert.ListJobsRequest()
let response = try mediaConvertClient.listJobs(createJobRequest).wait()
print(response)
```

Also to be clear I am working with the NIO2.0 branch because of dependency conflicts, however, I did confirm that this code produces the same result with release 3.1.0.

**Comment by adam-fowler** [comment]
Yeah found a way to re-create. Just ask for some endpoints. It looks like the Content-Type code was wrong for rest-json. I have a another PR on aws-sdk-swift-core https://github.com/swift-aws/aws-sdk-swift-core/pull/110 which resolves this.

As soon as it goes in, I'll pull across to nio2.0 as well.

**Comment by kyleishie** [comment]
Thank you very much! 😎👍🏼

**Comment by adam-fowler** [comment]
Fix is on nio2.0
