### ISSUE TITLE
Support S3 buckets that contain a "."

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift#180]
**Is your feature request related to a problem? Please describe.**
We don't support S3 buckets that contain a period in their name. This is because we are using virtual addressing for buckets and SSL does not like the additional period in the host name. 

We cannot just stop using virtual addressing as it will be required for all new buckets post Sep 2020. But it is not required for old buckets and they can still contain a period in their name so we need to support them.

**Describe the solution you'd like**
Options for fixing could be either we add an option to the S3Middleware to not do the virtual address conversion and somehow create some path to send options to Middleware. Or we could just not do the virtual address conversion if the bucket name contains a period.

**Additional context**
See PR https://github.com/swift-aws/aws-sdk-swift/pull/174 and Issue https://github.com/swift-aws/aws-sdk-swift/issues/173 for context.

**Comment by adam-fowler** [comment]
@jonnymacs @Yasumoto thoughts?

**Comment by jonnymacs** [comment]
considering it's a rule that periods break virtual hosting, I'd say just not do the virtual address conversion if the bucket name contains a period

**Comment by adam-fowler** [comment]
#198
