### ISSUE TITLE
Basic User Guide

### ISSUE THREAD

**Issue by duncangroenewald** [swift-aws/aws-sdk-swift#181]
I would like to use this SDK in a macOS application and its not clear whether this SDK can be used for this purpose or whether it will only work for server side applications.

It would be useful if there was a basic guide on what the types of apps the sdk can be used with and how to setup for use for each type of application.

In my case I would like to use an AWS SDK to access S3 services from within an existing macOS application using Xcode 10 and 11.

It's not entirely clear on what the best way to do this is.  As I understand it Xcode has some Swift Package manager features that allow you to add dependencies to your project - and I assume one of which could be this SDK.  Not surprisingly I can't find any menu option for doing so in Xcode 10 so I am guessing this must be a new feature in Xcode 11.

No count there are a few folks who could quickly put together a basic guide of what works and what doesn't to save the rest of us lots of time trying to figure it all out ourselves.

Much appreciated.

**Comment by adam-fowler** [comment]
Hi Duncan, 
sorry our documentation does assume some knowledge of the swift package manager. XCode 11 does have a feature for including SPM packages. Unfortunately there is a bug in the current implementation which means you have to jump through a few more hoops to get aws-sdk-swift to work in this way. See #167 

The other method is to create a xcodeproj from the Package.swift file. You can do this from the command line by entering `swift package generate-xcodeproj` while in the same folder. Once you have generated the xcodeproj you can include this in your own xcodeproj. To reduce the amount of libraries you bring in you can create your own Package.swift in another folder and include only the modules you require (see the example in our readme).

**Comment by adam-fowler** [comment]
@duncangroenewald I added some more detail to the readme. Is that an improvement?
