### ISSUE TITLE
boringssl_context_handle_fatal_alert(1874) [C1.1:1][0x13b2e1ae0] write alert, level: fatal, description: certificate unknown

### ISSUE THREAD

**Issue by duncangroenewald** [swift-aws/aws-sdk-swift#182]
**Describe the bug**
Not sure this is a bug - might be me not understanding the proper use of aws-sdk-swift.  In any event I am getting the following error when calling the function to list objects from an S3 bucket.

**To Reproduce**
func listBucket(){
        
        let bucket = "aaa-bbb-ccc.s3-ap-southeast-2.amazonaws.com"

        let s3 = S3(
            accessKeyId: "XXXXX",
            secretAccessKey: "YYYYY",
            region: .apsoutheast2
        )

        // Create Bucket, Put an Object, Get the Object
        let listObjectsRequest = S3.ListObjectsV2Request(bucket: bucket)

        s3.listObjectsV2(listObjectsRequest).always { result in
            
            print("\(result)")
        }

**Expected behavior**
result should contain a list of objects.

**Setup (please complete the following information):**
 - OS: macOS 10.15
 - Version of aws-sdk-swift: latest as at 12/10/2019
 - Authentication mechanism as per example code above

**Additional context**
none

**Comment by adam-fowler** [comment]
`bucket` is the bucket name not its full web address. In your example it should be `aaa-bbb-ccc`.

**Comment by duncangroenewald** [comment]
Ok, I’ll try that - thanks.   Otherwise it seemed pretty straight forward to add to Xcode 11 project using the menu - never had to jump through any hoops but haven’t tried running the tests.

**Comment by duncangroenewald** [comment]
Brilliant … that was easy.  Thanks
