### ISSUE TITLE
Comprehend Medical is missing the diagnosis field

### ISSUE THREAD

**Issue by ezhou7** [swift-aws/aws-sdk-swift#196]
Hi there,

I've noticed that there is no field for diagnosis name (`DX_NAME`) in this enum:
https://github.com/swift-aws/aws-sdk-swift/blob/master/Sources/AWSSDKSwift/Services/ComprehendMedical/ComprehendMedical_Shapes.swift#L482

It should look something like this:
```
public enum EntitySubType: String, CustomStringConvertible, Codable {
        case name = "NAME"
        case dosage = "DOSAGE"
        ...
        case quantity = "QUANTITY"
        case diagnosisName = "DX_NAME"
        public var description: String { return self.rawValue }
    }
```

Should just be a one line fix.  I tried making a pull request, but the repo isn't open access.
Thanks!

**Comment by adam-fowler** [comment]
The shape files are auto-generated from the model files amazon supplies, I'll have to check the documentation and model files to see what the exact discrepancy is and then add to the patching code.

**Comment by adam-fowler** [comment]
I checked the documentation and there is no mention of a DX_NAME type as a valid value for Entity.type in the api reference. But I found it in the developer guide. I'll add a patch

**Comment by ezhou7** [comment]
Thanks!
