### ISSUE TITLE
S3RequestMiddleware force unwraps URLs and causes unrecoverable crash.

### ISSUE THREAD

**Issue by t2davis** [swift-aws/aws-sdk-swift#199]
**Describe the bug**
When building an AWS s3 request, if an incorrect key (path) is provided to the request the S3RequestMiddleware class will crash when force unwrapping a URL within the `virtualAddressFixup` function. This should likely be handled more gracefully. 

**To Reproduce**
1. Create an S3 put request. Pass a key with an empty space in-between two words.
2. Crash

**Expected behavior**
Proper error handling to handle failures more gracefully.

**Setup (please complete the following information):**
 - OS: Linux & macOS
 - Version of aws-sdk-swift: 3.1.0
 - Authentication mechanism: IAM profile with access key and secret environment variables.

**Comment by adam-fowler** [comment]
This is fixed in 4.0.0 beta. Will bring fix back 3.x.x branch

**Comment by adam-fowler** [comment]
#200

**Comment by adam-fowler** [comment]
Fixed in 3.x.x branch. Will be in a release in near future
