### ISSUE TITLE
DynamoDB latency is in tens of milliseconds in Lambda

### ISSUE THREAD

**Issue by pkamppur** [swift-aws/aws-sdk-swift#202]
Sorry if this is the wrong place to report this kind of issue / ask for help. Please redirect me to a better place.

**Describe the bug**
I have a Lambda function written in Swift which does both GetItem and PutItem requests to a DynamoDB table in the same region.

Latency of DynamoDB requests is high, typically 30-50 ms.

Latency this high is very bad, considering Lambda is priced per 100 ms. Two DynamoDB calls would very likely break the threshold of 100 ms causing extra charges. This goes against the selling point of DynamoDB of `single-digit millisecond performance at any scale`. Also it doesn't make a very good user experience.

*NOTE:* I clipped numbers to whole integers for legibility, actual code prints numbers like `139.54198360443115`.

```
GetItem took 139 ms
GetItem took 52 ms
GetItem took 47 ms
GetItem took 43 ms
GetItem took 71 ms
GetItem took 41 ms
PutItem took 43 ms
PutItem took 34 ms
PutItem took 57 ms
PutItem took 34 ms
PutItem took 34 ms
PutItem took 37 ms
PutItem took 33 ms
```

Comparable **Node.js 10.x** code runs much faster:

```
loadSettings: 79.127 ms
loadSettings: 6.707 ms
loadSettings: 4.887 ms
loadSettings: 26.218 ms
loadSettings: 4.967 ms
loadSettings: 4.766 ms
saveSettings: 7.832 ms
saveSettings: 6.325 ms
saveSettings: 6.049 ms
saveSettings: 20.504 ms
saveSettings: 6.546 ms
saveSettings: 6.178 ms
```

Both Lambdas run with **1024 MB** of RAM in `eu-central-1` and the DynamoDB table is in the same region.

**Expected behavior**
I'd expect to be able to access DynamoDB from a Swift Lambda using AWS Swift SDK with single-millisecond performance, or at least close to it.

**Setup (please complete the following information):**
 - OS: AWS Lambda with custom Linux runtime
 - Version of aws-sdk-swift: tested with both `4.0.0` and `async-http-client`
 - Authentication mechanism: IAM Role on the Lambda

**Additional context**

Here's my **Swift** code in essence (GetItem, PutItem is very similar).

```
let dynamoDB = DynamoDB() // passed as a parameter to my actual function

// function is actually run in Kitura router handler, my Lambda handles multiple routes
func get(userId: String, dynamoDB: DynamoDB) {
    let getRequest = DynamoDB.GetItemInput(
        key: [
            "PK" : DynamoDB.AttributeValue(s: userId),
            "SK": DynamoDB.AttributeValue(s: "SETTINGS")
            ],
        tableName: "TableName")
    
    let startTime = Date()
    dynamoDB.getItem(getRequest)
        .map { result -> Void in
            let endTime = Date()
            log("GetItem took \((endTime.timeIntervalSinceReferenceDate - startTime.timeIntervalSinceReferenceDate) * 1000 ) ms")
            
            // ... actual handling code
            return ()
        }
}
```

This is my **Node.js** code (loadSettings, saveSettings code is very similar).

```
const AWS = require('aws-sdk');
const db = new AWS.DynamoDB.DocumentClient()

async function getSettings(db, userId) {
    console.time('loadSettings')

    const params = {
        TableName: "TableName",
        Key: {
            "PK": userId,
            "SK": "SETTINGS",
        }
    };

    const settingsResult = await db.get(params).promise()

    console.timeEnd('loadSettings')
}
```

I have **AWS_NODEJS_CONNECTION_REUSE_ENABLED** set to **1** in my Node.js lambda function env. It helps bring down the latency for subsequent DB requests.

Any ideas, help or pointers very much appreciated. Am I missing something obvious? I'm pretty new to AWS Swift SDK, Lambdas and DynamoDB, so maybe I just don't know something essential yet.

Lastly, thanks for this project!

**Comment by adam-fowler** [comment]
Thank you for your detailed bug.

At first glance, I would say the HTTP client we use (async-http-client) doesn't have a connection pool setup yet so connection re-use is not implemented in aws-sdk-swift. Once the connection pool work currently going on is complete we will be looking to make use of this in aws-sdk-swift. 

I wouldn't want to place all the blame there though. We need to look at the performance of our code as well (it was on my list).

**Comment by pkamppur** [comment]
Thanks for the swift reply! Looking forward to testing with connection pooling, when it comes available.

**Comment by fabianfett** [comment]
@pkamppur Most of the performance difference should come from the missing connection pooling in `AsyncHTTPClient` as @adam-fowler pointed out.

There is one thing that's interesting though:

Your first invocation is considerably slower than the consecutive ones, even in swift - where basically all invocations should remain more or less equal (since all the work has to be done every time). In your code though you point out that you only measure the time for the actual request - not the complete lambda invocation time.

Would you mind running your example again with **AWS_NODEJS_CONNECTION_REUSE_ENABLED** set to **0** and with the swift times from the `AsyncHTTPClient` branch?

Thanks so much in advance.

**Comment by pkamppur** [comment]
@fabianfett Hi! Thanks for the reply.

First invocation does seem to be slower than the other ones. Perhaps some internal network stack stuff is initialised during that, or some caches get warmed? And yes, I'm trying to measure just the DynamoDB request, not whole Lambda invocation duration.

I tested my Lambda with the different configurations you suggested. Here are the results:

**Node.js Without AWS_NODEJS_CONNECTION_REUSE_ENABLED**

```
loadSettings: 94.451ms
loadSettings: 25.728ms
loadSettings: 25.517ms
loadSettings: 33.424ms
loadSettings: 25.785ms
loadSettings: 22.703ms
loadSettings: 26.988ms
saveSettings: 26.624ms
saveSettings: 29.816ms
saveSettings: 26.538ms
saveSettings: 20.793ms
saveSettings: 28.085ms
saveSettings: 26.478ms
saveSettings: 31.437ms
saveSettings: 25.173ms
saveSettings: 29.654ms
```

**Swift with latest swift-aws/aws-sdk-swift:async-http-client**

```
GetItem SETTINGS took 129.04 ms
GetItem SETTINGS took 45.19 ms
GetItem SETTINGS took 40.48 ms
GetItem SETTINGS took 43.83 ms
GetItem SETTINGS took 37.82 ms
GetItem SETTINGS took 34.73 ms
GetItem SETTINGS took 42.43 ms
GetItem SETTINGS took 41.39 ms
GetItem SETTINGS took 41.12 ms
PutItem SETTINGS took 48.17 ms
PutItem SETTINGS took 47.25 ms
PutItem SETTINGS took 30.68 ms
PutItem SETTINGS took 39.20 ms
PutItem SETTINGS took 44.14 ms
PutItem SETTINGS took 36.86 ms
PutItem SETTINGS took 42.97 ms
PutItem SETTINGS took 32.53 ms
PutItem SETTINGS took 28.47 ms
PutItem SETTINGS took 40.52 ms
```

On average it seems that **Node.js** manages gets in 25 ms while it takes **Swift** 40 ms.

Hope this helps!

**Comment by adam-fowler** [comment]
@pkamppur what are you using to build your swift lambdas?

**Comment by pkamppur** [comment]
I'm using Docker locally on my Mac.

This is the contents of my **Dockerfile**:

```
FROM swift:5.1.2 as builder

RUN apt-get -qq update && \
	apt-get -q -y install openssl libssl-dev libcurl4-openssl-dev libicu-dev
```

This is the command run when building

```
swift build --build-path .build-linux -c release --product swift-api
```

One thing that came to mind about first invocation performance. How does Lambda get AWS access keys? I have a role configured to my Lambda. Does Lambda use EC2 metadata service locally to get access keys? Maybe getting those access keys explains the first invocation being slower that the rest?

**Comment by adam-fowler** [comment]
I am not 100% sure. I’ll have to verify. Using the ec2 instance metadata service would be an obvious cause of a longer initial request.

**Comment by fabianfett** [comment]
@pkamppur the access credentials are in the environment. If you want to you can supply them directly like here:

https://github.com/fabianfett/swift-aws-lambda/blob/master/Examples/TodoAPIGateway/Sources/TodoAPIGateway/main.swift

Though AFAIK aws-sdk-swift does this automatically (by grabbing them from env without Metadata roundtrip). The explicit way we would be sure though.

**Comment by adam-fowler** [comment]
If the environment variables are available aws-sdk-swift will use them

**Comment by adam-fowler** [comment]
I did a little bit of profiling. Basically recording times at different points in the process. The results are below. I ran PutItem 5 times. I used the a version of the master branch. This is using `eu-west-1` but results seem comparable to `eu-central-1`. I have recorded the time entering a function. Each time value is based off the start time of the request. So to get the time spent in a function subtract its time value from the next time value.

```
2019-12-02T06:48:06+0000 info: createAWSRequest: 0.005679
2019-12-02T06:48:06+0000 info: createNioRequest: 0.043753
2019-12-02T06:48:06+0000 info: invoke: 0.125016
2019-12-02T06:48:06+0000 info: validate: 0.183648
2019-12-02T06:48:06+0000 info: Done: 0.184154

2019-12-02T06:48:06+0000 info: createAWSRequest: 0.000049
2019-12-02T06:48:06+0000 info: createNioRequest: 0.000575
2019-12-02T06:48:06+0000 info: invoke: 0.001367
2019-12-02T06:48:06+0000 info: validate: 0.034385
2019-12-02T06:48:06+0000 info: Done: 0.035892

2019-12-02T06:48:06+0000 info: createAWSRequest: 0.000010
2019-12-02T06:48:06+0000 info: createNioRequest: 0.001113
2019-12-02T06:48:06+0000 info: invoke: 0.001790
2019-12-02T06:48:06+0000 info: validate: 0.034788
2019-12-02T06:48:06+0000 info: Done: 0.034962

2019-12-02T06:48:06+0000 info: createAWSRequest: 0.000039
2019-12-02T06:48:06+0000 info: createNioRequest: 0.001268
2019-12-02T06:48:06+0000 info: invoke: 0.001967
2019-12-02T06:48:06+0000 info: validate: 0.041244
2019-12-02T06:48:06+0000 info: Done: 0.041441

2019-12-02T06:48:06+0000 info: createAWSRequest: 0.000012
2019-12-02T06:48:06+0000 info: createNioRequest: 0.001164
2019-12-02T06:48:06+0000 info: invoke: 0.001872
2019-12-02T06:48:06+0000 info: validate: 0.036232
2019-12-02T06:48:06+0000 info: Done: 0.036383
```
The majority of time is spent between invoke and validate. This is basically the sending of the http request and receiving the response. Apart from the first run, only about 2ms is spent in aws-sdk-swift code. So any major improvements in speed will be coming from the http client.

The first request is quite interesting. Everything is considerably slower, not just the http request. Not knowing enough about the internals of swift my only explanation for this would be the code is being loaded into the instruction cache and possibly instruction cache misses are super expensive. If you run the lamba again immediately after the first invocation the first request runs in a similar amount of time to all the others.

**Comment by pkamppur** [comment]
Interesting. Speedup is 100x. Could it be that a lot of the underlying code relies on Objective-C runtime (via inheriting from NSObject, for example). ObjC runtime has method lookup caches etc. and getting those warm might explain this. I don't know. As you said, these seem to be only 2ms, and the actual network call dominates.

**Comment by adam-fowler** [comment]
@pkamppur No ObjC runtime on Linux.
Connection pool work on async-http-client seems to be bearing fruit https://github.com/swift-server/async-http-client/pull/105#issuecomment-557752567

**Comment by pkamppur** [comment]
Ah, true, I forgot that 😄

I was just reading that `async-http-client` PR! Hopefully pooling gets done soon 👍

**Comment by kylebrowning** [comment]
If y'all chime in on that thread/PR it may speed things up.

**Comment by adam-fowler** [comment]
Did a test with Trevor's connection pooling work. Results are rather good
```
    0.1745600700378418,
    0.004350066184997559,
    0.0045969486236572266,
    0.0045680999755859375,
    0.004562973976135254
```
If the lambda is already warm the first request is approx 0.04s

**Comment by pkamppur** [comment]
@adam-fowler Thanks for testing the pooling code, and thanks for reporting the problems you found! I'm sure that will make the pooling code get done sooner.

Your results look great, very consistent performance, and faster than Node.js!

**Comment by adam-fowler** [comment]
Latest build of aws-sdk-swift uses AsyncHTTPClient 1.2.0 which include Connection pooling. I did another Lambda test. This is the output from a DynamoDB test which calls PutItem 5 times and then GetItem 5 times (This is a warm lambda). Times are all based off the start time. I think we can say this is resolved.
```
START RequestId: cca3fb61-5dba-4ae6-9de0-3d091960aa6f Version: $LATEST
PutItem 0.0038559436798095703
PutItem 0.007524967193603516
PutItem 0.011169910430908203
PutItem 0.014629960060119629
PutItem 0.018123984336853027
GetItem 0.02192091941833496
GetItem 0.02530193328857422
GetItem 0.02902090549468994
GetItem 0.03218197822570801
GetItem 0.03525090217590332
END RequestId: cca3fb61-5dba-4ae6-9de0-3d091960aa6f
REPORT RequestId: cca3fb61-5dba-4ae6-9de0-3d091960aa6f	Duration: 36.13 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 73 MB	
```

**Comment by adam-fowler** [comment]
If I run all the PutIems in parallel and all the GetItems in parallel the Lambda execution time reduces to 14ms

**Comment by pkamppur** [comment]
Hi!

Sorry it took me so long to reply.

Excellent! Glad to see things got fast. Thanks!
