### ISSUE TITLE
Archiving and installing app via Xcode on device using AdHoc causes app to crash when trying to open it

### ISSUE THREAD

**Issue by duraz** [swift-aws/aws-sdk-swift#208]
**Describe the bug**
When archiving app to then export via AdHoc will cause the then installed app on device to crash when I try to open it after being installed.

**To Reproduce**
1. include AWS SDK via SwiftPM. 
2. archive [release...]
3. export AdHoc
4. drag .ipa on iOS device
5. tap on installed app on device
6. app crashes immediately

**Expected behavior**
It should archive properly so the app wouldn't crash

**Setup (please complete the following information):**
 - OS: iOS 13.2.3 (17B111)
 - Version of aws-sdk-swift 4.0.0
 - Authentication mechanism [hard-coded credentials]

**Additional context**
Using previous SDK via Carthage worked. Is there a way to install aws-sdk-swift over Carthage?

**Comment by duraz** [comment]
Using Xcode Version 11.2.1 (11B53)

**Comment by adam-fowler** [comment]
Hi @duraz 
I have a couple of questions
1) Does App Store Connect work?
2) You mention a previous SDK installed via Carthage. We've never had a Catharge version of aws-sdk-swift. Which previous SDK are you talking about?

I'm pretty sure this is an issue with Xcode not including packages that are dependencies of the packages you include. I'll need to verify that though.

**Comment by duraz** [comment]
@adam-fowler 
1. I haven't pushed anything up using the swift SDK since it was crashing in adhoc.
2. You are correct. I meant this https://github.com/aws-amplify/aws-sdk-ios. So, due to the SwiftPM crash, I ripped it out and recoded what I needed using that SDK installed via Carthage. I wish I could use the swift SDK, but due to the crash I had no other choice.

After posting this I did a lot of research and I would agree with you. Xcode seems to be doing something bad and causing this issue. I wish I would have known before installing the swift sdk, it would have saved me many hours.

So, here's my take. It would be nice to make the swift sdk available via carthage too. That would allow us to use the swift SDK still while Apple figures out SwiftPM issues.

Thank you

**Comment by adam-fowler** [comment]
aws-amplify/aws-sdk-ios is an amazon developed sdk for ios
aws-sdk-swift is a community developed effort. 

I'll continue to investigate this. I've ascertained it's not packages with dependencies that are the issue.

**Comment by hishma** [comment]
FWIW I think I may be experiencing a similar issue. 

In my case I get a  `EXC_BAD_ACCESS (SIGSEGV)` when I attempt to create a `S3.PutObjectRequest`, like so:

```
guard let data = data, !data.isEmpty else { return }

let putObjectRequest = S3.PutObjectRequest(acl: .publicRead, body: data, bucket: "my-bucket", contentLength: Int64(data.count), key: "my-key")
```

This only occurs when building an archive from Xcode (11.2.1), ether exported and installed on a device manually, or via TestFlight. 

• iOS 13.2.3
• swift-aws/aws-sdk-swift 4.0.0
• swift 5.0

**Comment by adam-fowler** [comment]
@duraz, @hishma Disabling dead code stripping seems to resolve this issue. You'll find if you build a release build and run that it'll crash. If you switch dead code stripping off release, Adhoc and TestFlight builds should work. 

See also https://github.com/apple/swift-nio/issues/1294

**Comment by hishma** [comment]
@adam-fowler Just confirming that the workaround does indeed seem to work.

Thanks!

**Comment by duraz** [comment]
This is a problem Apple has to fix. As far as disabling dead code stripping, that won't work for me. It affects my archived app size.
For now I'll wait to use aws-swift-sdk and keep using https://github.com/aws-amplify/aws-sdk-ios, luckily they provide Carthage support. A nice to have would be for this repo to support Carthage too...

It's unfortunate Apple releases dev tools that don't work.

I like this repo. I hope to be able to use it soon, as soon as Apple fixes their mess.

**Comment by adam-fowler** [comment]
@duraz one other option you could try is create an xcodeproj from the aws-sdk-swift Package.swift using `swift package generate-xcodeproj`. You can then add that project into your project. You would need to manually add the frameworks to your target for the services you are using and all their dependencies eg aws-sdk-swift-core, swift-nio, swift-nio-transport-services etc

I haven't tried this but it avoids the package manager and may work.

**Comment by adam-fowler** [comment]
This is resolve in XCode 11.3
