### ISSUE TITLE
SendMessageBatchResult schema does not match api

### ISSUE THREAD

**Issue by kyleishie** [swift-aws/aws-sdk-swift#212]
**Describe the bug**
The SQS. SendMessageBatchResult shape has two properties (failed and successful) that are non-optional however the api responds with optional fields.  This causes DecodingErrors to be thrown.

**To Reproduce**
1. Perform SQS.sendMessageBatch()
2. Watch response fail to decode

**Expected behavior**
I expected to receive a decoded SendMessageBatchResult instance with either failed or successful set.

**Setup (please complete the following information):**
 - OS: macOS
 - Version of aws-sdk-swift: 5.1
 - Authentication mechanism: aws profile

**Additional context**
I can submit a PR for this but I figured I'd start here.  I changed these properties to optional in my fork which does seem to fix the issue.

**Comment by adam-fowler** [comment]
Hi Kyle, you'll know already the service shapes and api are generated. Do you know how to edit the patch code in the Code Generator to get it to output the correct shape?

**Comment by kyleishie** [comment]
Ah... I did know that.  Just  not when it 11pm at night and I've been working all Sunday with the flu. 😅

I do NOT know how to update that but I'm willing to learn.

**Comment by adam-fowler** [comment]
Sorry to hear about your flu.
I'll do a pull request with the changes and add a description here as to what is happening.

**Comment by kyleishie** [comment]
Ok perfect!

**Comment by adam-fowler** [comment]
The aws-sdk-swift shape, api and error service files are generated from the json files in the models folder. We get these from amazon via the [aws-sdk-go](https://github.com/aws/aws-sdk-go) github repository. 

The app to do this conversion from model file to aws-sdk-swift services files can be found in the [CodeGenerator folder](https://github.com/swift-aws/aws-sdk-swift/tree/master/CodeGenerator) of the aws-sdk-swift repository. Go into this folder and type `open Package.swift` to load the project into the Xcode. 

The model files are not always correct, so we have to patch them before generating the `aws-sdk-swift` files. This patch process is part of the CodeGenerator and is run prior to parsing the dictionaries that have been loaded from the model json. The code for this can be found in [patch.swift](https://github.com/swift-aws/aws-sdk-swift/blob/master/CodeGenerator/Sources/CodeGenerator/patch.swift). 

At the top of this file you'll see a list of various shapes that have been patched. There are three types of patch (replace, add or remove). To work out what you need to patch you need to look at the `api-2.json` file for the service you are editing and find the definition of the shape you want to change. The most common patches are for renaming, or adding enum entries. There are a number of patches removing a variable from the "required" section of a shape. This is what you need to do for your issue. Once you have edited patch.swift you should run the CodeGenerator and new service files will be generated.

As AWS is returning a `SendMessageBatchResult` shape without the `successful` and `failed` fields the fields must be considered optional and cannot be required. The patch I added removes those fields from the required array. You can see this in PR #213.
