### ISSUE TITLE
Do we need the large AWSSDKSwift library in Package.swift

### ISSUE THREAD

**Issue by adam-fowler** [swift-aws/aws-sdk-swift#220]
We have a library AWSSDKSwift in Package.swift which is dependent on all the AWS services. Do we need this? Can anyone see a use case for including all that code in one library?

**Comment by Yasumoto** [comment]
Only thing I could think of was if [we used it as a dependency for the tests, but we don't](https://github.com/swift-aws/aws-sdk-swift/blob/master/Package.swift#L460). I can't think of anything, so probably solid to remove in `5.0`.

**Comment by adam-fowler** [comment]
added PR
