### ISSUE TITLE
Proposal: use the same AWSClient in multiple services

### ISSUE THREAD

**Issue by fabianfett** [swift-aws/aws-sdk-swift#231]
For 5.0.0 I propose the following change in the communication between a service generated by the CodeGenerator and the AWSClient from aws-sdk-swift-core:

### Proposal: 

I think we should offer the possibility to create a service with a client and reuse a client over multiple services.

Instead of an initializer reading like this:

```swift
    public init(
          accessKeyId: String? = nil, 
          secretAccessKey: String? = nil, 
          sessionToken: String? = nil, 
          region: AWSSDKSwiftCore.Region? = nil, 
          endpoint: String? = nil, 
          middlewares: [AWSServiceMiddleware] = [], 
          eventLoopGroupProvider: AWSClient.EventLoopGroupProvider = .useAWSClientShared) 
     {
        self.client = AWSClient(
            accessKeyId: accessKeyId,
            secretAccessKey: secretAccessKey,
            sessionToken: sessionToken,
            region: region,
            amzTarget: "DynamoDB_20120810",
            service: "dynamodb",
            serviceProtocol: ServiceProtocol(type: .json, version: ServiceProtocol.Version(major: 1, minor: 0)),
            apiVersion: "2012-08-10",
            endpoint: endpoint,
            serviceEndpoints: ["ca-central-1-fips": "dynamodb-fips.ca-central-1.amazonaws.com", "local": "localhost:8000", "us-east-1-fips": "dynamodb-fips.us-east-1.amazonaws.com", "us-east-2-fips": "dynamodb-fips.us-east-2.amazonaws.com", "us-west-1-fips": "dynamodb-fips.us-west-1.amazonaws.com", "us-west-2-fips": "dynamodb-fips.us-west-2.amazonaws.com"],
            middlewares: middlewares,
            possibleErrorTypes: [DynamoDBErrorType.self],
            eventLoopGroupProvider: eventLoopGroupProvider
        )
    }
```

This would lead to something like this. The ServiceConfig object would be supplied on every request. Being just a struct this should be fairly inexpensive.

```swift
    public init(
          client: AWSClient,
          endpoint: String? = nil, 
          middlewares: [AWSServiceMiddleware] = []) 
    {
        self.client = client
        self.config = ServiceConfig(
            region: region,
            amzTarget: "DynamoDB_20120810",
            service: "dynamodb",
            serviceProtocol: ServiceProtocol(type: .json, version: ServiceProtocol.Version(major: 1, minor: 0)),
            apiVersion: "2012-08-10",
            endpoint: endpoint,
            serviceEndpoints: ["ca-central-1-fips": "dynamodb-fips.ca-central-1.amazonaws.com", "local": "localhost:8000", "us-east-1-fips": "dynamodb-fips.us-east-1.amazonaws.com", "us-east-2-fips": "dynamodb-fips.us-east-2.amazonaws.com", "us-west-1-fips": "dynamodb-fips.us-west-1.amazonaws.com", "us-west-2-fips": "dynamodb-fips.us-west-2.amazonaws.com"],
            middlewares: middlewares,
            possibleErrorTypes: [DynamoDBErrorType.self],
        )
    }
```

This has IMHO a number of advantages:

- In most deployments an executable has one set of credentials allowing access to potentially multiple aws services. This is true for Lambda as well as Docker/ECS and should be true in most pure EC2 deployments (though I wonder if anyone does that). These credentials have to be injected into every AWS Service that is being used. If one want's to build their service on top of dependency injection currently credentials or complete service objects have to be passed into controllers or stores. With this approach one creates one AWSClient when starting up the server, passes this object around into the places where it is needed. Controllers/Stores can setup their own AWSService facade and use the object.
- This has also the advantage of making shutdowns easy (because needs to happen just once), when not injecting an AsyncHTTPClient.

```swift
// main.swift

let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
defer { try! group.syncShutdownGracefully() }

let awsClient = AWSClient(eventLoopGroup: group)
defer { aws.syncShutdown() }

// further startup

// run
```

**Comment by adam-fowler** [comment]
I can see how this could work. It would work quite well with Vapor configuration setup. In that we can provide an extension to Application which creates a member variable `aws:AWSClient`. This is the recommended method for Vapor 4.

Apart from `init()` the service apis would still look the same?

**Comment by adam-fowler** [comment]
One thing to note the `middlewares` can be specific to `ServiceConfig` but it would be good to also provide them at the client level as well. Also `endpoints` should be stored at the `ServiceConfig` level. They tend to be service specific. The client would probably be a holder for credentials, eventLoopGroup, HTTPClient and maybe some general purpose middlewares (eg Logging)

**Comment by fabianfett** [comment]
> Apart from init() the service apis would still look the same?

Yes!

**Comment by fabianfett** [comment]
We probably create the ServiceConfig with a CoW backing storage:

**Comment by adam-fowler** [comment]
> We probably create the ServiceConfig with a CoW backing storage.
> https://www.youtube.com/watch?v=iLDldae64xE
> Great talk by weissi.

Yes it's a good talk. But is ServiceConfig a value type? I would imagine `ServiceConfig` being a read only object and therefore could be a class without any of the issues associated with multiple references editing it. You could setup the CoW backing storage, or your could just change it from a struct into a class.

**Comment by adam-fowler** [comment]
I've been playing around with timings for struct copies vs class copies. You have to have quite a number of elements in a struct before a class copy is quicker (ref counting costs a lot). Stick a dictionary in a struct though and it automatically costs as much as a class copy.

**Comment by fabianfett** [comment]
As weissi pointed out: Don't make struct vs classes about performance. If it's a value type use structs. If performance is an issue use CoW. 

In my point of view this will be very clearly a value type. Just wanted to point out, if we run into problems we should think about CoW.

**Comment by adam-fowler** [comment]
I'm not sure it is an obvious value type. It is a readonly configuration object. Why would you keep copying it to use it?
