### ISSUE TITLE
Example Projects demonstrating Simple Functionality

### ISSUE THREAD

**Issue by robert-will-brown** [swift-aws/aws-sdk-swift#243]
**Is your feature request related to a problem? Please describe.**
I'm struggling with implementing some simple ideas using the [documentation](https://swift-aws.github.io/aws-sdk-swift/current/index.html).

**Describe the solution you'd like**
An example project(s) with the code, or linked from the README that shows basic (and optional advanced) functionally of the code in use that can be used in Xcode with minimal knowledge.  This would show real life workable examples that could be tailored for use elsewhere.

**Describe alternatives you've considered**
Persist with what's available!

Its worth stating that my swift skill level is not advanced, but neither is the requirements for my application so a quick project to bootstrap this would be super helpful for me.

**Comment by robert-will-brown** [comment]
Its worth stating that my swift skill level is not advanced, but neither is the requirements for my application...😃

**Comment by adam-fowler** [comment]
What are you trying to do? The api is so large it would be hard to cover even a small amount with examples. We are reliant on amazon providing documentation in the model files that we build the sdk files from. 

If there isn’t enough documentation you can always look at the official amazon docs https://docs.aws.amazon.com/. These provide both user guide and api reference documentation. If you need help with the swift implementation and how to work with swift nio objects like EventLoopFuture there is swift nio documentation here  https://apple.github.io/swift-nio/docs/current/NIO/index.html  

First tell us what you are trying to do and I’ll see if I can help.

**Comment by adam-fowler** [comment]
Here is an example of using the AWS service CognitoIdentityProvider  https://github.com/adam-fowler/aws-cognito-authentication/blob/master/Sources/AWSCognitoAuthenticationKit/Authenticatable.swift

**Comment by robert-will-brown** [comment]
Thanks for the info and examples @adam-fowler.

> First tell us what you are trying to do and I’ll see if I can help.
For myself some simple, (I presume) examples I could use would be:

1. List all my S3 buckets
1. List contents of an S3 bucket
1. List all my EC2 instances
1. Interact with EC2 - for example power an instance off
1. List all my SQS Queues
1. Show the number of SQS messages in a given queue

I would guess that some of these (1 & 3 & 5) would be very similar code.  I appreciate these could be very simple examples for some, but would certainly help bootstrap my understanding with some concrete examples and usage.

**Comment by adam-fowler** [comment]
As aws-sdk-swift uses swift-nio it is useful to familarize yourself with its concepts especially [EventLoopFuture](https://apple.github.io/swift-nio/docs/current/NIO/Classes/EventLoopFuture.html). The basic setup for any communication with AWS is as follows. I am assuming you have read the AWS credentials of the [readme](https://github.com/swift-aws/aws-sdk-swift#configuring-credentials) 

```swift
// create service object
let client = Service(region: <my-region>)
// create input object
let input = Service.Input(<parameters>)
// pass input to service client. This returns an swift NIO EventLoopFuture. This is a container
// object which will be populated with the response from AWS sometime in the future 
let eventLoopFuture = client.command(input)
```
Once you have the `EventLoopFuture` you can syncronously wait on its result as follows
```swift
let result = try eventLoopFuture.wait()
```
Add a closure to be run when the eventLoopFuture is successful
```swift
eventLoopFuture.whenSuccess { response in 
   print(response)
```
As I said earlier you should read the EventLoopFuture [documentation](https://apple.github.io/swift-nio/docs/current/NIO/Classes/EventLoopFuture.html) to get a full idea of what is possible.

Given the above, listing S3 buckets would be as follows (NB there is no input object for this command)
```swift
let s3 = S3(region: .useast1)
let buckets = try s3.listBuckets().wait()
```
Listing the files in a bucket using `EventLoopFuture.whenSuccess` can be done as follows
```swift
let s3 = S3(region: .useast1)
let input = S3.ListObjectsRequest(bucket: "mybucket")
let future = s3.listObjects(input)
future.whenSuccess { response in 
   let contents = response.contents
   print(contents)
}
```
You can see examples of both of these in the sample Vapor project I have [here](https://github.com/adam-fowler/aws-vapor-test/blob/master/Sources/App/Controllers/S3Controller.swift)

There is a one-one correspondance between AWS API calls and the api calls in aws-sdk-swift so you should be able to use the official [AWS documentation](https://docs.aws.amazon.com/) api reference to work out how to do the others examples you suggested.

**Comment by adam-fowler** [comment]
Updated readme. Give better description of where API is coming from ie REST interfaces, Added link to Amazon docs, reordered docs to make better sense.

**Comment by robert-will-brown** [comment]
Many thanks Adam.
