### ISSUE TITLE
Multipart upload blocks EventChannel with file reading IO

### ISSUE THREAD

**Issue by bridger** [swift-aws/aws-sdk-swift#244]
I believe the code for uploading multipart files blocks the EventLoop with IO.

If I understand it right, this closure is reading data in a blocking way: https://github.com/swift-aws/aws-sdk-swift/blob/624305c09f4098431a20421c1e5243704fa6fc25/Sources/AWSSDKSwift/Extensions/S3/S3%2Bmultipart_API.swift#L204

I see there is a task already to use NIO.NonBlockingFileIO for the upload: https://github.com/swift-aws/aws-sdk-swift/issues/222 There are a couple other options that could fix the issue as well
- Move the file reading to a different thread. Not ideal, but better than blocking an EventLoop.
- Support sending a FileRegion, which can be sent on a Channel without loading it into memory at all.

**Comment by adam-fowler** [comment]
#271 fixes this.
I have also added https://github.com/swift-server/async-http-client/pull/202 so we can supply AsyncHTTPClient with `FileRegions`
