### ISSUE TITLE
Feature Request: Gzip on upload and download to S3

### ISSUE THREAD

**Issue by bridger** [swift-aws/aws-sdk-swift#248]
I'd like to start storing my files on S3 gzipped. Ideally, I could enable a flag on the multipart upload and multipart download APIs to transparently gzip the data when uploading, and then transparently unzip (if appropriate) the data when downloading.

When the files are local (not on S3), they shouldn't be gzipped.

The API could handle the headers when uploading and downloading:
- The content-encoding header should be set on the uploaded object to indicate it is gzipped. I believe content-length is also required.
- When downloading, the multipart API would check the headers. If the Content-Encoding shows it is gzipped and the "auto unzip" flag is on, then it would unzip before saving to the local file.

**Comment by adam-fowler** [comment]
I do something similar myself but have kept it separate from aws-sdk-swift.

I don't know enought about the zlib but it might be possible to stream the compressed data to generate fixed part sizes. If not I'm not sure how you would do this.

I'm not sure when I would get to this. If you cannot wait you can use the versions of the multipart upload that stream data via a closure to implement a version of this.

**Comment by bridger** [comment]
No rush! If I have time I might get to this too. I just wanted to document the use case.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adam-fowler** [comment]
I found by using AsyncHTTPRequest we can get decompression for free. You just need to setup a `HTTPClient` with decompression enabled.

**Comment by adam-fowler** [comment]
Hi @bridger,
I'm not sure compression/decompression is really something that should be part of aws-sdk-swift. But I have built a compression library that work with NIO ByteBuffers https://github.com/adam-fowler/swift-nio-compress that you could use. 

If you use this along with the 5.0 alpha version of aws-sdk-swift. You could do the following to upload a file
```
import NIOCompress

    func uploadFile(fileInByteBuffer: inout ByteBuffer, s3Client: S3) throws -> S3.PutObjectOutput {
        let compressedBuffer = try fileInByteBuffer.compress(with: .gzip)
        let putObjectRequest = S3.PutObjectRequest(
            body: .byteBuffer(compressedBuffer),
            bucket: bucketName,
            contentEncoding: "gzip",
            key: "myfile")
        return try s3Client.putObject(putObjectRequest).wait()
    }
```
You could do an equivalent function for download and decompress or you can create an S3 client that has response decompression enabled (something that comes with AsyncHTTPClient).
```
    func downloadFile() throws -> Data? {
        let httpClient = HTTPClient(eventLoopGroupProvider: .createNew, configuration: .init(decompression: .enabled(limit: .none)))
        defer {
            try? httpClient.syncShutdown()
        }
        let s3 = S3(region:.euwest1, httpClientProvider: .shared(httpClient))
        let getObjectRequest = S3.GetObjectRequest(bucket: "mybucket", key: "myfile")
        let getObjectResponse = try s3.getObject(getObjectRequest).wait()
        return getObjectResponse.body
    }
```

**Comment by bridger** [comment]
Amazing! I'll give these approaches a try soon. Thank you for the update!

**Comment by adam-fowler** [comment]
Ok I’m gonna close this now
