### ISSUE TITLE
lambda.invoke throws InvalidSignatureException if invocation / log type is set

### ISSUE THREAD

**Issue by ephemer** [swift-aws/aws-sdk-swift#256]
**Describe the bug**

Doing this:

```
let request = Lambda.InvocationRequest(functionName: lambdaFunctionName, invocationType: .event, payload: payload)
// OR:
let request = Lambda.InvocationRequest(functionName: lambdaFunctionName, logType: .tail, payload: payload)

lambda.invoke(request)
```

Fails every time with `InvalidSignatureException: `, `The operation couldn’t be completed. (AWSSDKSwiftCore.AWSResponseError error 1.)`.

If I leave the `logType` or `invocationType` as the default (`nil`), the operation succeeds. I can see that these two parameters are being added internally as a header to the request to AWS. It appears they will be signed alongside the payload and other request headers

I can only imagine that something is being including in the signature that should be left unsigned, but I must admit I have only a vague idea of how this signing normally works.

Invoking the function as an event via the CLI or other APIs succeeds.

**To Reproduce**

See above. All lambda functions fail when specifying invocation or log type. I've tried different lambda functions all in the `eu-central-1` region.

**Expected behavior**

I need to be able to specify the `event` invocation type for asynchronous operations.

**Setup (please complete the following information):**
 - OS: mac OS Catalina 15.2
 - Version of aws-sdk-swift: `.package(url: "https://github.com/swift-aws/Lambda.git", .upToNextMajor(from: "4.0.0"))`
 - Authentication mechanism: credentials from the CLI as stored with `aws configure`. I do have two sets of credentials stored, but the SDK seems to be using the correct credentials (the default). Entering the keys directly in code doesn't make a difference.

**Additional context**

I tried adding the logging middleware but it didn't really help:

```
Request:
  Invoke
  POST https://lambda.eu-central-1.amazonaws.com/2015-03-31/functions/---MY-FUNCTION---/invocations
  Headers: [
    X-Amz-Log-Type : Tail
  ]
  Body: data (260 bytes)
```

**Comment by ephemer** [comment]
I updated to 4.2.1 (which seems to be the latest) and I get a more detailed error reponse, but still the same error:

> Request:
>   Invoke
>   POST https://lambda.eu-central-1.amazonaws.com/2015-03-31/functions/----/invocations
>   Headers: [
>     X-Amz-Log-Type : Tail
>   ]
>   Body: data (260 bytes)
> Response:
>   Status : 403
>   Headers: [
>     Connection : close
>     Date : Fri, 20 Mar 2020 00:17:11 GMT
>     Content-Type : application/json
>     x-amzn-ErrorType : InvalidSignatureException
>     Content-Length : 192
>     x-amzn-RequestId : a03f0d4b-0418-407f-b590-2cdf8da4e087
>   ]
>   Body: 
>   {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
> InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> The operation couldn’t be completed. (AWSSDKSwiftCore.AWSResponseError error 1.)
> InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> InvalidSignatureException
> InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
> Optional("The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.")

**Comment by adam-fowler** [comment]
@ephemer Thanks for posting this. I'll have to investigate but your comments about removing certain headers do make sense.

Could you add the headers `X-Amz-Log-Type` and `X-Amz-Invocation-Type` to the following array in the 4.x.x branch of aws-sdk-swift-core https://github.com/swift-aws/aws-sdk-swift-core/blob/ce148f908d84c582debacae8c5433e9c79031a2c/Sources/AWSSDKSwiftCore/Signers/V4.swift#L34 and see if that fixes it.

**Comment by adam-fowler** [comment]
If you could also test `InvocationRequest.clientContext` along with header `X-Amz-Client-Context` that'd be great.

**Comment by ephemer** [comment]
Hi @adam-fowler, thanks for your quick response here!

I will happily give that a try, I need to figure out how to get this building locally though so I can make the change. I remember SwiftPM had a feature for this but I haven’t used it in years..

**Comment by adam-fowler** [comment]
> I will happily give that a try, I need to figure out how to get this building locally though so I can make the change. I remember SwiftPM had a feature for this but I haven’t used it in years..

.package(path: “path-to-local-repo)

**Comment by adam-fowler** [comment]
@ephemer looks like this might be an issue with the actual signer. The lambda calls work fine on the master branch which has a new signing code. The 4.x.x release branch is broken. Given I have a working signer I should be able to fix the 4.x.x version as well.

**Comment by ephemer** [comment]
@adam-fowler awesome! What do you need from me for this?

**Comment by adam-fowler** [comment]
I think I can take it from here.

**Comment by adam-fowler** [comment]
The issue was the signer needs to create a canonical request string which include the requests headers listed in two different places. These both have to be in the same order. One of these was being ordered before all the strings were lowercased and one was being ordered after all the strings were lowercased. I'm rather surprised this has never come up before.

This fix is on the 4.x.x branch at the moment. I'll do a release in the next few days

**Comment by adam-fowler** [comment]
This is now released in https://github.com/swift-aws/aws-sdk-swift-core/releases/tag/4.2.4

**Comment by ephemer** [comment]
@adam-fowler thanks so much for figuring this out! We ended up not calling any lambda functions at all (it was quicker to just process our work locally) but I'm sure I'll revisit this some day and am glad to see this fixed
