### ISSUE TITLE
CloudSearchDomain upload document's contentType does not set correctly

### ISSUE THREAD

**Issue by kingreza** [swift-aws/aws-sdk-swift#285]
Requesting to upload a simple JSON data through CloudSearchDomain returns a 

`{ ["Content-Type header must be one of ['application/xml', 'application/json'] (was binary/octet-stream)"] }`

even though the request specifically sets the contentType to `.applicationJson`

**To Reproduce**
1. instantiate a `cloudSearchService` like this:
```
let cloudSearchService = CloudSearchDomain(
  accessKeyId: "ACCESSKEY", 
  secretAccessKey: "SECRETKEY", 
  sessionToken: nil, 
  region: .uswest2, 
  endpoint: "https://{Document domain listed in the dashboard}",
  middleware: [], 
  eventLoopGroupProvider: .useAWSClientShared
)
```
1. Encode a simple struct to json using encodable:
```
let jsonData = try! JSONEncoder().encode(segment)
```
Where segment is defined:
```
  struct IndexSegment: Codable {
    let id: Int
    let episode_title: String
    let guest: String
    let keywords: [String]
    let text: String
  }
```
2. Create a `CloudSearchDomain.UploadDocumentsRequest` request
```
let request = CloudSearchDomain.UploadDocumentsRequest(
  contentType: .applicationJson, 
  documents: jsonData
)
```
3. Upload the data to the CloudSearch domain
```
cloudSearchService.uploadDocuments(request).whenComplete { result in
  switch result {
  case .success(let response):
    print(response)
   case .failure(let error):
      print(error)
    }
 }
```

**Expected behavior**
At this point, I expect to get a successful response from AWS which would indicate whether the new document was added/updated or deleted. But instead, get 
```
{ ["Content-Type header must be one of ['application/xml', 'application/json'] (was binary/octet-stream)"] }
```

even though the content type is set to `.applicationJson`
**Setup (please complete the following information):**
 - OS: macOS Catalina 10.15.5 Beta
 - Version of aws-sdk-swift [4.6.0]
 - Authentication mechanism [hard-coded credentials]

**Comment by adam-fowler** [comment]
I have a fix for this on the 4.x.x branch of aws-sdk-swift-core. https://github.com/swift-aws/aws-sdk-swift-core/commit/13738adc1603e4b50ae6aa3f758fc44f51e46aa3. If you could test this that'd be great

**Comment by kingreza** [comment]
How can I set the dependency branch for `swift-aws/aws-sdk-swift-core` specifically? I can set the branch for `aws-sdk-swift` which seems to resolve to the [master branch ](https://github.com/swift-aws/aws-sdk-swift/blob/master/Package.swift#L245) of `swift-aws/aws-sdk-swift-core` for all the targets. 

I'm using XCode 11.4 and the package manager integrated with it.

**Comment by kingreza** [comment]
Nevermind, I forked the repo and changed the package to point toward 4.x.x for core. The issue is fixed. Thanks!

**Comment by adam-fowler** [comment]
The easiest way to test is to drag the aws-sdk-swift-core folder into xcode on top of your project. 

I’ll do a new release in the next day or so.

**Comment by adam-fowler** [comment]
A new release of `aws-sdk-swift-core` https://github.com/swift-aws/aws-sdk-swift-core/releases/tag/4.5.1 has been released. This is patch release so you should be able to pick it up by selecting menu item "Swift Packages"->"Update to Latest Package Versions"
