### ISSUE TITLE
EC2: The parameter instanceInitiatedShutdownBehavior is not recognized

### ISSUE THREAD

**Issue by coredumped** [swift-aws/aws-sdk-swift#291]
**Describe the bug**
I've been trying to launch an EC2 instance from a macOS app I'm working on using a snippet like this:

```
let rq = EC2.RunInstancesRequest(
 dryRun: dryRun ? true : nil, 
 imageId: imageID, 
 instanceInitiatedShutdownBehavior: ephemeral ? .terminate : .stop, 
 instanceType: itype.awsInstanceType, 
 keyName: keypairName,  
 maxCount: 1, 
 minCount: 1, 
 securityGroups: securityGroups, 
 tagSpecifications: tagSpec, 
 userData: userdata
)
```
And this is the result:
```
UnknownParameter: The parameter instanceInitiatedShutdownBehavior is not recognized
  ▿ unknownParameter : 1 element
    ▿ message : Optional<String>
      - some : "The parameter instanceInitiatedShutdownBehavior is not recognized"
```
Even if I omit using the instanceInitiatedShutdownBehavior so it uses the default value of nil I still get the same error, additionally, if I try to use `dryRun = true` it also says that *The parameter dryRun is not recognized*.

**To Reproduce**
1. Just try a similar code snippet.

**Expected behavior**
An EC2 instance should have been created but it didn't.

**Setup (please complete the following information):**
 - OS: macOS
 - Version of aws-sdk-swift: From Xcode 4.6.0 - Next major
 - Authentication mechanism: hard coded credentials.

**Additional context**
Add any other context about the problem here. If this a bug related to a command not working can you run the same command on a client initialised with the logging middleware. eg `S3(region: .useast1, middlewares:[AWSLoggingMiddleware()])`
Using:
`EC2(accessKeyId: accessKey, secretAccessKey: secret, region: .uswest1, middlewares:[AWSLoggingMiddleware()])`

```
Request:
  RunInstances
  POST https://ec2.us-west-1.amazonaws.com/
  Headers: []
  Body: 
  Action=RunInstances&ImageId=ami-0002de7a49fd7a133&InstanceType=t2.micro&KeyName=vFF_keypair_dbg&MaxCount=1&MinCount=1&SecurityGroup.1=default&SecurityGroup.2=vFFsecgroup&TagSpecification.1.Tag.1.key=vFF.vmtype&TagSpecification.1.Tag.1.value=vpn&TagSpecification.1.Tag.2.key=vFF.ephemeral&TagSpecification.1.Tag.2.value=false&UserData=CANNOT_SHOW_USERDATA_SORRY&Version=2016-11-15&instanceInitiatedShutdownBehavior=terminate
Response:
  Status : 400
  Headers: [
    Transfer-Encoding : chunked
    Server : AmazonEC2
    Connection : close
    Date : Thu, 14 May 2020 17:37:39 GMT
  ]
  Body: 
  <Response><Errors><Error><Code>UnknownParameter</Code><Message>The parameter instanceInitiatedShutdownBehavior is not recognized</Message></Error></Errors><RequestID>cc124def-5cac-4fc8-a297-51d5292f8a26</RequestID></Response>
```

From AWS documentation I can see that the correct parameter name is ` InstanceInitiatedShutdownBehavior` instead of `instanceInitiatedShutdownBehavior`.

I've already forked this repo and would like to contribute a PR to fix this if possible, is that ok?

**Comment by adam-fowler** [comment]
Are you using 4.x.x or the 5.x.x alpha? Sometimes these parameters naming issues are a more global issue so I would like to investigate. The aws json model files are explicit about the parameter being lowercase, but then as you point out the docs indicate otherwise. It could be an error in the json model file. There are a number of other parameters which seem to be lowercase in the EC2 models which the docs say are uppercase.

If it is an error in the json, you will need to update the patch.swift file in the CodeGenerator and run the CodeGenerator again. The CONTRIBUTING doc indicates how to re-generate the code but unfortunately the way we patch the json has changed since the CONTRIBUTING doc was written. It now uses KeyPaths as I am loading the JSON via Codable now.

**Comment by adam-fowler** [comment]
EC2 has its own protocol. It is very similar to the query protocol used by SNS, IAM, STS etc but has some minor differences. It appears it requires all query params to have their first letter capitalized. I can't just capitalize them in the shapes file though as some shapes are used in both requests and responses and the responses require the opposite. 

EC2 is a law unto itself :-(. I'll have to add something to the aws-sdk-swift-core to work around this.

**Comment by adam-fowler** [comment]
https://github.com/swift-aws/aws-sdk-swift-core/pull/253

**Comment by coredumped** [comment]
Hi, I did look into patch.swift and even added one *patch* there but as you said with so many inconsistencies with the json model file just adding patch after patch is a too cumbersome *solution*.

I did have dealings with the official Amazon SDK for iOS in the past and specifically with EC2, there was an issue where the error response was not being deserialized properly. So as you said **EC2 is a law unto itself** :-D

**Comment by adam-fowler** [comment]
I have a branch of aws-sdk-swift-core 4.x.x that should fix this issue https://github.com/swift-aws/aws-sdk-swift-core/tree/ec2-query-4xx. I haven't been able to test it properly yet. If you wanna give it a go, download a local copy and drag the folder into your project in XCode to see if it fixes the issues you are seeing.

**Comment by coredumped** [comment]
Hi, I'm testing against master at this moment, and at least until now, it seems to be working great!

Thanks

**Comment by coredumped** [comment]
Hello, everything seems fine from my side, I think it is safe to close this issue.

Thanks a lot!
