### ISSUE TITLE
Upload Large File Example

### ISSUE THREAD

**Issue by fenixkim** [swift-aws/aws-sdk-swift#308]
Please, add a sample of how to upload a large file (.zip 1GB) to AWS S3 using the `multipartUpload` method with this great library.

Please, help me to understand how to do that.

Thanks

**Comment by adam-fowler** [comment]
Because the S3 multipart functions are quite complex we have provided a helper function `S3.multipartUpload`. The function below uses it to upload a file using the multipart API. The `partSize` is the size of each part loaded. It has to be higher then 5MB. The closure is called after each part is uploaded.

```
func uploadWithMultipart(bucket: String, key: String, filename: String, partSize: Int) -> EventLoopFuture<S3.CompleteMultipartUploadOutput> {
    let request = S3.CreateMultipartUploadRequest(bucket: bucket, key: name)
    return s3.multipartUpload(request, partSize: partSize, filename: filename) { 
        print("Progress \($0*100)%") 
    }
}
```

The upload needs a `NIOThreadPool` for the file loading, by default this is created and destroyed by the function, but you can provide your own by including the parameter `threadPoolProvider: .shared(myThreadPool)`.

**Comment by fenixkim** [comment]
Hey Adam, thank you so much for your prompt response.

I understand your example, that's where I started, but I got stuck uploading the parts with `uploadPart`. Unfortunately, I'm new in Swift, especially in SwifNIO. It is a totally new concept for me.

If you add a full example, starting from a local URL of a large file. It could be very helpful for me and for this repository.

For example, how to chunk a large file and use the `uploadPart` method with that chunk, and append to the multipart request, and then complete it.

I appreciate any additional lhelp.

**Comment by adam-fowler** [comment]
Hey @fenixkim with the code I supplied, you don't need to worry about calling uploadPart etc. The function does all the work for you. You only need to call it with a filename, chunk size you require it to be broken up into. It will then call the `createMultipartUpload`, `uploadPart` and `completeMultipartUpload` commands for you. You can find the code [here](https://github.com/swift-aws/aws-sdk-swift/blob/ed203c0c02eb4ab7fd3d3fb1ba232aa9f9931fd9/Sources/AWSSDKSwift/Extensions/S3/S3%2Bmultipart_API.swift#L228).

If you call the above function as follows it will do everything
```
_ = try uploadWithMultipart(bucket: "myBucket", key: "myKey", filename: "reallyBig.zip", partSize: 16*1024*1024).wait()
```

**Comment by fenixkim** [comment]
Hey Adam, you are the best!!

Thanks for the clarification!
