### ISSUE TITLE
AWS S3 Copy Object validation requires "/" prefix

### ISSUE THREAD

**Issue by pankajsoni19** [swift-aws/aws-sdk-swift#311]
**Describe the bug**

branch: 3.3.0

```
 let oldAWSKey = awsFilePaths.removeFirst()
    var newAWSKey = "\(oldAWSKey)"
    newAWSKey.removeLast()  // remove 1 character from end
    
    let sourcePath = "\(handler!.config.awsBucket)/\(oldAWSKey)"
    let copyReq = S3.CopyObjectRequest(bucket: handler!.config.awsBucket, copySource: sourcePath, key: newAWSKey)
    
    handler!.s3.copyObject(copyReq).map { (result: S3.CopyObjectOutput) -> Void in
        print("result: \(result)")
    }
```
**To Reproduce**

1. create object with private acl
2. try to copy object within same bucket and same folder changing its name

**Expected behavior**

* copied object should be visible in s3

**Setup (please complete the following information):**
 - OS: MacOS | Ubuntu
 - Version of aws-sdk-swift: 3.3.0
 - Authentication mechanism: IAM Credentials with full AWS access

**Comment by pankajsoni19** [comment]
trying to copy object
sourcePath: above::  `my-bucket/media/random-uuid.mp4)`
to same bucket & folder
key: above : `media/random-uuid.mp4`

error printed: 
```
ValidationError: CopyObjectRequest.copySource ()) does not match pattern \/.+\/.+.
```

**Comment by adam-fowler** [comment]
Hi @pankajsoni19, 
Can you run this with the `AWSLoggingMiddleware` so I can see the requests.

**Comment by pankajsoni19** [comment]
I ran the code through java sdk.

the issue is the regex pattern validation that is done on inputsource field.
if you see my input field it contains `)` character which is not valid as per regex and thus request gets rejected. Why the regex is even there?

**Comment by adam-fowler** [comment]
The regex is there because that is the regex the S3 json model files say should be applied to keys when copying files. The S3 model files not being correct is not necessarily a surprise though.

**Comment by pankajsoni19** [comment]
can you apply this validation check when object gets created too? or can you provide some option to remove this check?

**Comment by adam-fowler** [comment]
> can you apply this validation check when object gets created too? or can you provide some option to remove this check?

I'll go for fixing the validation. v3.x hasn't had updated service files for a while. Maybe it has been fixed since

**Comment by adam-fowler** [comment]
It's nothing to do with the ")". The regex expects `/bucket/key`. You are supplying `bucket/key`. The documentation is a little confusing here as it says you need to supply the second case, but then says the regex from the first case should be applied.

I verified without the regex both case work. You should be able to resolve this by prefixing your key with "/"

**Comment by adam-fowler** [comment]
Can you verify that prefixing your key with "/" resolves the issue?

**Comment by adam-fowler** [comment]
This is fixed for 5.x.x #312 and prefixing with "/" should work
