### ISSUE TITLE
How to Abort a Multipart Upload Request.

### ISSUE THREAD

**Issue by fenixkim** [swift-aws/aws-sdk-swift#316]
Hey @adam-fowler, days ago you help me to understand how to upload with multipart. #308

This time, I want to understand how to cancel that upload. I know there is a function `AbortMultipartUploadRequest`, but it requires an `uploadId` and in don't know how to get that `uploadId` using your previous solution.

What is the best way to cancel the multipart upload?

I appreciate any help.

**Comment by adam-fowler** [comment]
You can throw an error from the progress closure, to quit the upload. This will do all the clean up for you

**Comment by fenixkim** [comment]
Hey, thanks again. That was just what I needed!
