### ISSUE TITLE
`AWSLoggingMiddleware` does not log errors

### ISSUE THREAD

**Issue by pokryfka** [swift-aws/aws-sdk-swift#326]
**Describe the bug**
`AWSLoggingMiddleware` does not log errors.
This is because `AWSClient` runs middleware on the response after it is validated.

**To Reproduce**

```
let s3client = S3(middlewares: [AWSLoggingMiddleware()], httpClientProvider: .createNew)
try s3client.getObject(.init(bucket: "invalidBucket", key: "invalidKey")).wait()
```

there is a log entry for request, see example below, but none for response

```
Request:
  GetObject
  GET https://invalidBucket.s3.us-east-1.amazonaws.com/invalidKey
  Headers: []
  Body: empty
```

**Expected behavior**
I think it makes sense to to be able to run middleware on the response before validation;
that way the response could be "fixed" or at the very least logged.

This affects `AWSLoggingMiddleware` as well other "loggers" like [`XRayMiddleware`](https://github.com/pokryfka/aws-xray-sdk-swift) I created.

**Setup (please complete the following information):**
 - OS: macOS 10.15.5, Amazon Linux
 - Version of aws-sdk-swift: 5.0.0-alpha4
 - Authentication mechanism: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variables (locally and run as Lambda function)

**Additional context**
When sending the request:

```
    public func send<Output: AWSDecodableShape>(operation operationName: String, path: String, httpMethod: String, on eventLoop: EventLoop? = nil) -> EventLoopFuture<Output> {
        let eventLoop = eventLoop ?? eventLoopGroup.next()
        let future: EventLoopFuture<Output> = credentialProvider.getCredential(on: eventLoop).flatMapThrowing { credential in
            let signer = AWSSigner(credentials: credential, name: self.serviceConfig.signingName, region: self.serviceConfig.region.rawValue)
            let awsRequest = try self.createAWSRequest(
                        operation: operationName,
                        path: path,
                        httpMethod: httpMethod)
            return awsRequest.createHTTPRequest(signer: signer)
        }.flatMap { request in
            return self.invoke(request, on: eventLoop)
        }.flatMapThrowing { response in
            return try self.validate(operation: operationName, response: response)
        }
```

an error is thrown based on the status code:
```
                    // if it returns an HTTP status code outside 2xx then throw an error
                    guard (200..<300).contains(response.status.code) else { throw AWSClient.InternalError.httpResponseError(response) }
```

in which case `validate` (which runs the middleware) is not called.

---

While in `validate`, middleware will not be run if creating of a `AWSResponse` failed

```
        var awsResponse = try AWSResponse(from: response, serviceProtocol: serviceConfig.serviceProtocol, raw: raw)

        // do we need to fix up the response before processing it
        for middleware in serviceConfig.middlewares + middlewares {
            awsResponse = try middleware.chain(response: awsResponse)
        }
```

**Comment by adam-fowler** [comment]
The logging middleware is only designed to log requests/responses. It isn't really setup for errors. We intend to bring in proper logger support in the near future. See https://github.com/swift-aws/aws-sdk-swift-core/issues/274

**Comment by adam-fowler** [comment]
Added the error output to `AWSLoggingMiddleware` anyway https://github.com/swift-aws/aws-sdk-swift-core/commit/c5d4fda28322a1aded8573873921d0c6c99c392e

**Comment by pokryfka** [comment]
Thank you, will check it out.

BTW is there any schedule for releasing v5.0.0?

**Comment by adam-fowler** [comment]
When we get it done :-b. Sorry this is done in everyone's spare time. We have one or maybe two more alpha releases. The next will include a lot of changes and I am hoping we can get that out in the next 2 weeks. The one after that will be refining what we have and shouldn't be that long after that. I might consider that the beta.
