### ISSUE TITLE
ApiGateway.RestApi.binaryMediaTypes become nil

### ISSUE THREAD

**Issue by noppoMan** [swift-aws/aws-sdk-swift#33]
binaryMediaTypes property in api response seems String Type

**Comment by adam-fowler** [comment]
Don't know if this occurs on other services but when an array only has one element it seems that ApiGateway outputs it as ```"element"``` instead of ```["element"]```

**Comment by adam-fowler** [comment]
fixed in https://github.com/swift-aws/aws-sdk-swift-core/pull/103

**Comment by adam-fowler** [comment]
Found the cause of this. The hal+json reports an array with a single value just as the value. But multiple values as an array.
