### ISSUE TITLE
Sample for usage with vapor for streaming uploads to S3

### ISSUE THREAD

**Issue by rossedwardsus** [swift-aws/aws-sdk-swift#334]
**Is your feature request related to a problem? Please describe.**

I would like to be able to upload a file to s3 but with streaming from vapor as opposed to a file.  But the only sample is for putObject.

**Describe the solution you'd like**

An additional sample of using this library with Vapor with streaming uploads would be great.  I am using this on a side project where a focus will be on photo uploads.  I have been able to get the putobject part to work but its my understanding this doesn't work with multipart.  I see there is a mention of using multipart but that seems IOS specific as it uses a file as opposed to a streaming object.

**Describe alternatives you've considered**

For now i will just use putObject.  Or another language for this part of the project. 

**Additional context**

**Comment by adam-fowler** [comment]
I would recommend you return a signed URL back to your client for them to upload the image to S3 themselves. Don’t waste your Vapor server time passing image data from your client to S3. When I’m nearer a computer I’ll post some code.

**Comment by adam-fowler** [comment]
@rossedwardsus If you are running on AWSSDKSwift 4.x.x the following code should return a signed URL for you. Pass this URL back to your user and they can use it to upload their file to S3. The URL expires within one hour.
```
let s3 = S3()
s3.client.signURL("https://<mybucket>.s3.<region>.amazonaws.com/<myfile>", httpMethod: "PUT", expires: 3600)
```

**Comment by rossedwardsus** [comment]
Thanks!
