### ISSUE TITLE
Assertion failure in +[NSValueTransformer awsmtl_JSONArrayTransformerWithModelClass:] AWS Cognito

### ISSUE THREAD

**Issue by TheRedCamaro30** [swift-aws/aws-sdk-swift#340]
I am using the api gateway swift sdk for my project when I initialize my client the and set up the AWSService configuration I receive an error and the application crashes. Please note that there is no authorization required to access my api however without setting a credentials provider the application crashes saying that the AWSSignatureV4Signer  was found nil.

1) declare credentials provider
 let credentialsProvider = AWSCognitoCredentialsProvider(regionType: AWSRegionType.USEast1, identityPoolId: "us-east-1:*******")
    let configuration = AWSServiceConfiguration(region: AWSRegionType.USEast1, credentialsProvider: credentialsProvider)
    
    AWSServiceManager.default().defaultServiceConfiguration = configuration
    let client = COMBINEDATACombinedDataClient.default()
2) call a client method in my case a POST request

The client should call the api and get back the results from the API call

Setup
 - OS: iOS 13.6
 - Version of  
AWSAPIGateway (2.15.0)
AWSCore (2.15.0)
 - Authentication mechanism [hard-coded credentials, IAM Instance Profile on EC2, etc]
None however for the code to run as descibed above I am using an aws cognito identiy

**Additional context**
The error I am recieving is as such 

`Assertion failure in +[NSValueTransformer awsmtl_JSONArrayTransformerWithModelClass:]`

```
 Caught exception Expected an array of dictionaries, got: {
    code = 28P01;
    file = "auth.c";
    length = 104;
    line = 337;
    name = error;
    routine = "auth_failed";
    severity = FATAL;
```

**Comment by adam-fowler** [comment]
@TheRedCamaro30 ?
