### ISSUE TITLE
Error when connecting to RDS Aurora through RSDDataService

### ISSUE THREAD

**Issue by erickva** [swift-aws/aws-sdk-swift#345]
**Describe the bug**
I am trying to connect to Aurora from my Swift Lambda function.
But I am receiving the following error on CloudWatch:
```
warning Lambda : lifecycleIteration=4 lambda handler returned an error: 
The request url database-1.cluster-cf4nbtzweamy.us-east-1.rds.amazonaws.com 
must specify url host and scheme is invalid format.
This error is internal. So please make a issue on
https://github.com/swift-aws/aws-sdk-swift/issues to solve it.
```
This is all new to me, so I am following the instructions and opening an issue :)

**To Reproduce**
This is the code that I am using:
```
let rdsDataService = RDSDataService(client: AWSClient(httpClientProvider: .createNew),
                         region: .useast1,
                         partition: Partition.aws,
                         endpoint: "database-1.cluster-cf4nbtzweamy.us-east-1.rds.amazonaws.com")
```

**Expected behavior**
I am expecting a successful connection so I can execute: `rdsDataService.executeStatement`

**Setup (please complete the following information):**
 Swift AWS Lambda Runtime

**Comment by adam-fowler** [comment]
You need to add "https://" in front of your url. Like this
```
let rdsDataService = RDSDataService(client: AWSClient(httpClientProvider: .createNew),
                         region: .useast1,
                         partition: Partition.aws,
                         endpoint: "https://database-1.cluster-cf4nbtzweamy.us-east-1.rds.amazonaws.com")
```

**Comment by adam-fowler** [comment]
@erickva did that fix your issue?

**Comment by erickvafinstro** [comment]
Somewhat, the error went away. But I did not manage to connect to RDS. But that would be related to other problems I suppose. I think you can close this ticket. Thank you.
