### ISSUE TITLE
Missing region ap-northeast-3 

### ISSUE THREAD

**Issue by gee1k** [swift-aws/aws-sdk-swift#348]
Missing region `ap-northeast-3`。Asia Pacific (Osaka-Local)

https://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by gee1k** [comment]
I am using v4.7.0

**Comment by adam-fowler** [comment]
Fixed https://github.com/swift-aws/aws-sdk-swift/releases/tag/4.8.0
