### ISSUE TITLE
[Question] - What is the recommended way to sign an AWS request using AWSSignerV4?

### ISSUE THREAD

**Issue by yuriferretti** [swift-aws/aws-sdk-swift#361]
Hi all, 

I'm going to create an ElasticSearch Service that will live on a VPC instead of exposing a public IP address so only my compute resources which correct IAM policies will be able to reach it.

To achieve that my AWS compute resources will need to make [signed requests to ES domain endpoints](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html) and I would like to know how is the best way to sign those requests using [AWSSignerV4](https://github.com/swift-aws/aws-sdk-swift-core/blob/main/Sources/AWSSignerV4/signer.swift).

**Comment by adam-fowler** [comment]
If you are calling ElasticSearch commands, you can setup `ElasticsearchService` to use a custom endpoint.
```
let elasticSearch = ElasticsearchService(endpoint: "https://my-endpoint")
```
If you just want to sign a URL you can do this via the `ElasticsearchService` client. It is preferable you do this via the client rather than through `AWSSignerV4`.
```
elasticSearch.client.signURL(url: URL, httpMethod: String, expires: Int = 86400)
```

In v5 which is currently in alpha you can call 
```
elasticSearch.signURL(url: URL, httpMethod: String, expires: Int = 86400)
```
This returns a `EventLoopFuture<URL>` as the service credentials might not be ready at that point.

**Comment by yuriferretti** [comment]
> If you are calling ElasticSearch commands, you can setup ElasticsearchService to use a custom endpoint.

I'm going to make calls to index, update and delete documents so I think this customs endpoint is not going to work.

> If you just want to sign a URL you can do this via the ElasticsearchService client. It is preferable you do this via the client rather than through AWSSignerV4.

I will need to also use request's body when signing because I'll need to make `PUT` and `POST` requests when I need to create or update a document. In this case do I need to use `AWSSignerV4` directly?

If so, do you think it would be a nice to add [signHeaders](https://github.com/swift-aws/aws-sdk-swift-core/blob/main/Sources/AWSSignerV4/signer.swift#L56) and [signURL](https://github.com/swift-aws/aws-sdk-swift-core/blob/main/Sources/AWSSignerV4/signer.swift#L84) to AWSClient?

**Comment by adam-fowler** [comment]
Not sure you can have unsigned payloads with ElasticsearchService,so you are probably best using `AWSSigner.signHeaders`.

If you want to use `AWSSigner` you can do it as follows. 
```
let credentials: Credential = StaticCredential(accessKeyId: "MYACCESSKEY", secretAccessKey: "MYSECRETACCESSKEY")
let signer = AWSSigner(credentials: credentials, name: "es", region: "MYREGION")
let headers = signer.signHeaders(
    url: URL(string: "https://MYURL")!, 
    method: .PUT, 
    headers: MYHEADERS, 
    body: .data(MYDATA)
)
```

**Comment by yuriferretti** [comment]
> Not sure you can have unsigned payloads with ElasticsearchService,so you are probably best using `AWSSigner.signHeaders`.
> 
> If you want to use `AWSSigner` you can do it as follows.
> 
> ```
> let credentials: Credential = StaticCredential(accessKeyId: "MYACCESSKEY", secretAccessKey: "MYSECRETACCESSKEY")
> let signer = AWSSigner(credentials: credentials, name: "es", region: "MYREGION")
> let headers = signer.signHeaders(
>     url: URL(string: "https://MYURL")!, 
>     method: .PUT, 
>     headers: MYHEADERS, 
>     body: .data(MYDATA)
> )
> ```

Thanks for your help!

Earlier you mentioned:
> In v5 which is currently in alpha you can call

> elasticSearch.signURL(url: URL, httpMethod: String, expires: Int = 86400)
This returns a EventLoopFuture<URL> as the service credentials might not be ready at that point.

Please let me know if you think is worth adding http header signing capabilities to the AWSClient and I will gladly submit a PR adding this feature following the same lines the of `signURL` methods.

**Comment by adam-fowler** [comment]
I'd rather not add the header signing wrapper to AWSClient and increase the public API surface. It is mainly used internally and this is the first case where I have seen it to needed elsewhere. So I think the method above should suffice.

I added signURL to the AWSClient because I see a request for that at least once every week.

thanks anyway

**Comment by adam-fowler** [comment]
I'm gonna close this if we are done

**Comment by yuriferretti** [comment]
thanks @adam-fowler closing it

**Comment by adam-fowler** [comment]
@yuriferretti don't know if you noticed I ended up adding a `signHeaders` function which is available from all service objects. So now you can do the following
```swift
func elasticSearchExecute(url: String, method: HTTPMethod, headers: HTTPHeaders, body: AWSPayload = .empty) -> EventLoopFuture<HTTPClient.Response> {
    let es = ElasticsearchService(client: awsClient, region: .useast1)
    return es.signHeaders(
        url: URL(string: url)!,
        httpMethod: method,
        headers: headers,
        body: body
    ).flatMap { headers in
        let request = try! HTTPClient.Request(
            url: url,
            method: method,
            headers: headers,
            body: body.asByteBuffer().map { .byteBuffer($0) }
        )
        return httpClient.execute(request: request, logger: logger)
    }
}
```
