### ISSUE TITLE
Consider using `var` instead of `let` in a request struct

### ISSUE THREAD

**Issue by novi** [swift-aws/aws-sdk-swift#56]
All of request models in this SDK use `let` for its parameters.

```swift
public struct ContainerDefinition: AWSShape {
    public let memoryReservation: Int32?
    public let portMappings: [PortMapping]?
    ...
}
```

But it could not change those params after initialize it.

Changing the `let` to `var`, we could build a parameter and update anytime.

```swift
var myContainer = ContainerDefinition(name: "api")
myContainer.memory = 256
let theContainer = containerDefinition
```

**Comment by noppoMan** [comment]
@novi  
Thanks for making an issue!
I totally agree with your opinion and I've been thinking, but this change might occur a controversial issue. Cause the struct that is used in a `FooRequest` sometimes referenced from `FooResponse` too. If we change `let` to `var`, the changes affect all of structs not only `Response`.
It means we can change `Response` value anytime.

What do you think this?

**Comment by adam-fowler** [comment]
Closing this
