### ISSUE TITLE
Does this work for IOS development?

### ISSUE THREAD

**Issue by martinbradford** [swift-aws/aws-sdk-swift#67]
Has anyone tried this SDK for IOS development? I'm developing applications running under Linux that access AWS cloud services and my wife is doing the same as IOS applications - it would be useful if we could build around a common source base!

**Comment by adam-fowler** [comment]
As the SDK in reliant on Swift-NIO it is not really suitable for iOS

**Comment by AlejandroJL** [comment]
Hello!

In the Apple repository there is an extension to use Swift-nio in iOS and tvO https://github.com/apple/swift-nio-transport-services.

I tried to make this work without having to make changes in the new beta of Xcode and iOS 13. But it does not stop working. But I will continue trying but making changes. I think it would be great if this would work on mobile devices because it allows you to create process management and monitoring tools.

**Comment by adam-fowler** [comment]
If you get Swift NIO working on iOS I would be interested to hear.

**Comment by adam-fowler** [comment]
@AlejandroJL I had a look at this and I should be able to get something running in the near future.

**Comment by AlejandroJL** [comment]
> If you get Swift NIO working on iOS I would be interested to hear.

Ok I will try


> @AlejandroJL I had a look at this and I should be able to get something running in the near future.

I think I do not understand what you mean

---

On the other hand I have seen that there is a pull request to support NIO 2.0. I'll make a folk of that PR to work in support for iOS

https://github.com/swift-aws/aws-sdk-swift-core/pull/72
https://github.com/swift-aws/aws-sdk-swift/pull/134

**Comment by adam-fowler** [comment]
@AlejandroJL checkout the ios branch, looks like I got it working

**Comment by AlejandroJL** [comment]
@adam-fowler I will check!

**Comment by AlejandroJL** [comment]
@adam-fowler I am preparing an example using the EMR service. It seems that everything works! Thanks @adam-fowler !!

**Comment by AlejandroJL** [comment]
@adam-fowler works!

**Comment by adam-fowler** [comment]
@AlejandroJL I've setup a new repository for this version https://github.com/swift-aws/aws-sdk-appleos. It treats all apple platforms as first class clients

**Comment by AlejandroJL** [comment]
Thanks @adam-fowler !!
