### ISSUE TITLE
ReplicationStatus.complete should be completed

### ISSUE THREAD

**Issue by tengyifei** [swift-aws/aws-sdk-swift#68]
See https://github.com/noppoMan/aws-sdk-swift/blob/ae8b82371280086cf81c4525331c9b69e860f403/Sources/AWSSDKSwift/Services/s3/S3_Shapes.swift#L1516

But AWS docs uses `COMPLETED`: https://docs.aws.amazon.com/AmazonS3/latest/dev/crr-status.html

Hence under the current code, you can't get objects from any replicated buckets. Doing so will result in a `DecodingError`.

**Comment by noppoMan** [comment]
We need to update Models to recent one. Just moment please.

**Comment by tengyifei** [comment]
I see. I think even the official Amazon SDK got it wrong (complete vs. completed). Need to find somewhere to file a bug report.
