### ISSUE TITLE
Include Support for S3 Pre-Signed URLs

### ISSUE THREAD

**Issue by sdnakhla** [swift-aws/aws-sdk-swift#73]
Adding pre-signed URLs would be a huge addition in terms of data security for us.

https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html
https://docs.aws.amazon.com/cli/latest/reference/s3/presign.html

**Comment by kyleishie** [comment]
Just in case anyone ends up here looking for the pre-signing functionality like I did.

This functionality does exist and is publicly accessible, however, the API doesn't resemble the other AWS SDK's that amazon demonstrates in their documentation.  Here is an example for signing an S3 PutObject URL for the us-east-1 region.

```
import AWSSDKSwiftCore

let credential = Credential(accessKeyId: "KeyId", secretAccessKey: "Secret")
let signer = Signers.V4(credential: credential, region: .useast1, service: "s3", endpoint: nil)
let urlToSign = URL(string: "https://mybucket.s3.amazonaws.com/path/to/file/key")!
let presignedURL = signer.signedURL(url: urlToSign,  method: "PUT", date: Date(), expires: 180)
```

Obviously it is not a good idea to hardcode your credentials like I've shown here, so feel free to use one of the CredentialProviders that have been implemented in the library.

**Comment by adam-fowler** [comment]
Hi guys,
I added a public api for generating signed URLs to AWSClient.
```
let s3 = S3(.euwest1)
let url = "https://mybucket.s3.amazonaws.com/key/for/my/file"
let signedURL = s3.client.signURL(url: url, httpMethod: "GET")
```
