### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by rsworden59** [swift-aws/aws-sdk-swift#82]
Could you provide some instructions on how to install this package?
I'm not new to XCode and not very new to Swift, but new to SPM.
What do we do after downloading this?
How do we build it? I tried and got an error.
How do we tell our project in XCode to reference this package so Import will work?

Thank you.

**Comment by Yasumoto** [comment]
Howdy, @rsworden59 ! Sorry to hear about the trouble! In this case, it looks like it's an issue with the openssl bindings. This is used by [`NIOOpenSSL`](https://github.com/apple/swift-nio-ssl) for networking.

Take a look at the [installation notes](https://github.com/apple/swift-nio-ssl#installation)— have you run `brew install libressl`? If you do that and it still doesn't work, would you mind posting a bit more of the error (as much as possible would be appreciated!)

**Comment by rsworden59** [comment]
@Yasumoto Thanks for that... I guess I forgot the Darwin reference would apply to MacOS. Now I was able to use **swift build** and it compiled the NIOOpenSSL which had been failing, and successfully linked. That created a bunch of stuff in the .build subdir so I think I've got it built.

How do I get this built package linked into my app in Xcode? Since the built library is in the (hidden) .build directory, XCode > General > Linked Frameworks > + > Add Other doesn't browse to there... I'm thinking there's another step to make it visible. There doesn't seem to be a lot of info about SPM in XCode 9.

The Installation section on Swift Package Manager just shows a Package.swift snippet. It contains a dependency reference back to GitHub, so I don't know how that relates to building a library on my local machine...

**Comment by rsworden59** [comment]
Found some other info implying I should "swift package generate-xcodeproj" which succeeded. Now I have AWSSKDSwift.xcodeproj. XCode > General > Linked Frameworks > + > Add Other was able to add and link it. But a simple app that tries to use **import AWSSDKSwift** gets "No such module AWSSDKSwift" although my project shows it:

![image](https://user-images.githubusercontent.com/33914803/44635277-1b989200-a958-11e8-9de9-cb9a7d3f6792.png)

Maybe we can work the correct steps into the Installation document (without including a full SPM tutorial!).

**Comment by Yasumoto** [comment]
@rsworden59 I think a slightly different approach is going to be best here.

Since [Xcode doesn't yet support SwiftPM](https://forums.swift.org/t/roadmap-of-swiftpm-integration-into-xcode/13466/10), your best bet is to do development of `aws-sdk-swift` using the package manager, but then to import it for an iOS or macOS project, use [Carthage](https://github.com/Carthage/Carthage#quick-start) to include it in that project as a dependency.

Note that Step 4 of that guide will fail with a missing `.xcodeproj` file. It will check out this git repo in your `Checkouts` directory, but you're going to need to `cd` into that directory and run `swift package generate-xcodeproj`. After that, move back to your top-level project directory and re-run `carthage update` and continue with Step 5.

I haven't tried this process with this codebase yet, but it's worked for several of my other projects in the past (for both iOS and macOS builds).

**Comment by rsworden59** [comment]
Hmph. I thought with Swift and XCode being Apple products that SPM was supposed to work with them. OK, I'll try the Carthage route. At least that link has a step-by-step guide. 

> do development of aws-sdk-swift 
That was never my goal.  ;-). Just trying to get AWS-SDK-Swift installed so I can adapt my existing XCode-Swift app to discover AWS instances etc. Sigh. Bigger effort than I expected.

Thanks.

**Comment by rsworden59** [comment]
I built a simple Cartfile containing just the following, patterned after the SWP info (since there's no info on how to set it for Carthage). 
github "swift-aws/aws-sdk-swift.git" ~>1.0.0

Carthage build fails with:
*** Skipped building aws-sdk-swift due to the error:
Dependency "aws-sdk-swift" has no shared framework schemes

I built a local .xcodeproj for aws-sdk-swift and examined it in XCode and I can see the shared scheme named "aws-sdk-swift-master-Package". But that's in my local copy... seems that the GitHub dependency has no such scheme?

**Comment by rsworden59** [comment]
I don’t know enough about packages and so I had to quit that effort. All
the instructions for installing under SPM or Carthage assume more base
knowledge. For now I’m learning to do the queries I need in the AWS CLI and
can shell out to get there. Probably fast enough for my needs. I may come
back to this method in the future. Maybe XCode and SPM will converge by
then.

**Comment by Yasumoto** [comment]
Sounds good, we're still working hard on making this usable and better documentation. The CLI should be 👌 , especially for now.
