### ISSUE TITLE
Precondition-fail in Swift-NIO

### ISSUE THREAD

**Issue by everlof** [swift-aws/aws-sdk-swift#93]
I use version 2.0.2 of "aws-sdk-swift".

Using the code below, I get a precondition failure in Swift-NIO.

```
            let bucket = "xxx-storage"
            let s3 = S3(
                accessKeyId: "MY_ACCESS_KEY",
                secretAccessKey: "MY_SECRET_ACCESS_KEY)


            // Upload text file to the s3
            let bodyData = "hello world".data(using: .utf8)!
            let putObjectRequest =
                S3.PutObjectRequest(acl: .publicRead,
                                    bucket: bucket,
                                    contentLength: Int64(bodyData.count),
                                    key: "hello.txt",
                                    body: bodyData)
            let ret = try s3.putObject(putObjectRequest)
```

I  looks like this:

<img width="974" alt="screenshot 2018-12-13 at 11 35 47" src="https://user-images.githubusercontent.com/1321434/49933176-438e1000-fecb-11e8-98fc-ddf8715c5219.png">

I can't really solve it myself. I see there's some comments regarding the code:

`//TODO(jmca) don't block`

And:

```
//TODO(jmca) learn how to map response to validate and return
// a future of generic Output: AWSShape
```

Anyone know how this could be solved?

**Comment by jonnymacs** [comment]
@everlof ok yes, I see this as well. Looks like this code was added since we integrated nio, but it is a good addition as indicated by the list of reasons that invoking wait on the main event loop is a bad idea.

https://github.com/apple/swift-nio/blame/master/Sources/NIO/EventLoopFuture.swift#L801

Until we have support for running nio requests w/o the invoking wait you need to wrap calls in a DispatchQueue.global().async {} block

try

```
DispatchQueue.global().async { 
 let ret = try s3.putObject(putObjectRequest)
}
```

**Comment by jonnymacs** [comment]
@everlof any luck?

**Comment by everlof** [comment]
Thanks for the feedback! I Haven't had time to try it out yet, other things got in the way. Ill be sure to update here as soon as I've tried the workaround!

**Comment by jonnymacs** [comment]
this is resolved in 3.x
