### ISSUE TITLE
Fatal error when connecting to DynamoDB.

### ISSUE THREAD

**Issue by ADGrant** [swift-aws/aws-sdk-swift#95]
Get Fatal error: Unexpectedly found nil while unwrapping an Optional val 

#7	0x00000001018a2f4c in Signers.V4.signedHeaders(url:headers:method:date:bodyData:) at .build/checkouts/aws-sdk-swift-core.git--8673986503349919441/Sources/AWSSDKSwiftCore/Signers/V4.swift:96
#8	0x000000010181e60d in AWSClient.nioRequestWithSignedHeader(_:) at .build/checkouts/aws-sdk-swift-core.git--8673986503349919441/Sources/AWSSDKSwiftCore/AWSClient.swift:217
#9	0x000000010181de57 in AWSClient.createNIORequestWithSignedHeader(_:) at .build/checkouts/aws-sdk-swift-core.git--8673986503349919441/Sources/AWSSDKSwiftCore/AWSClient.swift:190
#10	0x0000000101819737 in AWSClient.createNioRequest(_:) at .build/checkouts/aws-sdk-swift-core.git--8673986503349919441/Sources/AWSSDKSwiftCore/AWSClient.swift:243
#11	0x000000010181d70f in AWSClient.send<A, B>(operation:path:httpMethod:input:) at .build/checkouts/aws-sdk-swift-core.git--8673986503349919441/Sources/AWSSDKSwiftCore/AWSClient.swift:171
#12	0x0000000101094273 in DynamoDB.getItem(_:) at .build/checkouts/aws-sdk-swift.git--2129101693774578373/Sources/AWSSDKSwift/Services/DynamoDB/DynamoDB_API.swift:91

code in signedHeaders(url: URL, headers: [String: String], method: String, date: Date = Date(), bodyData: Data) -> [String: String]

          var headersForSign = [
                "x-amz-content-sha256": hexEncodedBodyHash(bodyData),
                "x-amz-date": datetime,
                "Host": url.hostWithPort!, // Forced unwrap fatal error is here 
            ]

**Comment by jonnymacs** [comment]
@ADGrant can you share your code to initialize DynamoDB? Are you setting the `endpoint` by any chance?

**Comment by jonnymacs** [comment]
@ADGrant ok that's what I suspected. Try initializing without the `endpoint`. This is an optional value that is set automatically based on the service and region.

`region` is also optional, and you can leave it out. The default is `.useast1` so you should be good, but if you need to specify a different region this is ideally bet set by an env variable `AWS_DEFAULT_REGION`.

If you must set an endpoint (and this is true for any of the services) it must include the protocol. ex: `https://dynamodb.us-east-1.amazonaws.com` So this is another option.

Meanwhile, there's an argument that force unwrap here is not a good idea. So I will add a guard around this code in a future release to surface a more helpful error.

**Comment by ADGrant** [comment]
Thanks, I will try that. I agree that force unwrap is not a good idea here (or in most places, particularly on server side code). One thing that would be helpful would be some simple examples using these APIs.

**Comment by ADGrant** [comment]
Works now. Thank you for the prompt assistance.

**Comment by jonnymacs** [comment]
@ADGrant you're welcome. 

And good suggestion on examples. We'll work on this. 

PRs are always welcome too :smiley:

**Comment by adam-fowler** [comment]
Closing as I don’t think there is anything to add here
