### ISSUE TITLE
S3 listObjectsV2 Hangs waiting for response

### ISSUE THREAD

**Issue by dashadrick** [swift-aws/aws-sdk-swift#96]
I'm using Mac OS 10.14.2 aws-sdk-swift 2.0.2 S3 and my request is hanging on the following call, however, I don't believe it has to do with the specific call.

This hangs:

    let request = S3.ListObjectsV2Request(bucket: bucketName)
    let response = try s3.listObjectsV2(request)

This is working fine:

    let request = S3.ListObjectsRequest(bucket: bucketName)
    let response = try s3.listObjects(request)

It appears to be hanging in:

    extension AWSClient {
        fileprivate func invoke(_ nioRequest: Request) throws -> Response {
            let client = HTTPClient(hostname: nioRequest.head.headers["Host"].first!, port: 443)
            let future = try client.connect(nioRequest)
    
            //TODO(jmca) don't block
            let response = try future.wait()

**Comment by jonnymacs** [comment]
@dashadrick ok. Thank you for submitting this issue. I think I see the problem in the aws-sdk-swift-core lib, it's dropping `list-type=2` param from the request. I'll have a new tag available shortly, by Monday for sure.

Thanks again.

**Comment by jonnymacs** [comment]
@dashadrick I've merged a fix into the master branch. I tested it myself, but would you be willing to try it before I tag a new release?

**Comment by dashadrick** [comment]
@jonnymacs I ran the same tests with version 2.0.3 release and both requests are working fine.  Sorry I missed this prior to you tagging the new release.
